### ISSUE TITLE
Content reflow documentation has a content-reflow issue

### ISSUE THREAD

**Issue by roryashfordbentley** [w3c/wcag#3449] opened 2023-10-06 10:47 UTC
Hi team, while reviewing the [ 1.4.10 Understanding Success Criteria](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) I noticed that the documentation page is currently failing criteria 1.4.10.

Beneath the heading "Example 1: Responsive Design" there is a video embed that is causing horizontal scrolling on the site.

To fix this, a CSS `max-width` of 100% can be applied to the video element but there may be more favourable approaches and techniques within the sites styling framework.

Apologies if this is the wrong place for this feedback.

![Screenshot 2023-10-06 at 11 45 20](https://github.com/w3c/wcag/assets/878484/8e9bded2-42e2-4cbb-8f68-d1d7ad0c033a)

**Comment by patrickhlauke** [comment] 2023-10-06 11:42
Duplicate of https://github.com/w3c/wcag/issues/3401

**Closed by patrickhlauke** 2023-10-06 11:42 UTC
