### ISSUE TITLE
Dead anchor link on page "Understanding SC 1.3.5: Identify Input Purpose (Level AA)"

### ISSUE THREAD

**Issue by lyudmil** [w3c/wcag#3382] opened 2023-09-11 10:57 UTC
### Steps to repro

1. Load https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose
2. In the "Success Criterion" section, click on the link [Input Purposes for user interface components section](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose#input-purposes)

### Expected result

The browser should jump to the section identified by the anchor `#input-purposes`, containing the purposes an input field can serve to pass the criterion.

### Actual result

The user remains in the "Success Criterion" section.

It looks like the link above is just dead. Here's the relevant console output:

```
> document.getElementById('input-purposes')
< null
```

**Comment by msayoung** [comment] 2024-02-27 16:32
Duplicate of:  https://github.com/w3c/wcag/issues/2962

**Comment by patrickhlauke** [comment] 2024-02-27 20:03
Agreed. Closing in favour of #2962

**Closed by patrickhlauke** 2024-02-27 20:03 UTC
Labels: Technical (bug)
