### ISSUE TITLE
Example not accessible

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#112] opened 2015-08-17 11:08 UTC
Name: Laurent Montaigne
Email: laurent@extension-interactive.com
Affiliation: Extension interactive
Document: TD
Item Number: SCR19
Part of Item: Examples
Comment Type: technical
Summary of Issue: Example not accessible
Comment (Including rationale for any proposed change):
If JavaScript is disabled, we can't see and we can't chose an item in the second select element.
 
Proposed Change:
If Javascript is disabled, we need to see all content in each select element and we need to add a server side control to check if items choosen in the two select element can match together

**Comment by MakotoUeki** [comment] 2015-08-17 12:10
I think it would depend on the web content technologies relied upon. If JavaScript is one of "the web content technologies relied upon" for the web content, it doesn't matter as long as it is accessibility-supported way of using JavaScript  If not, authors should do something when JavaScript is disabled.

**Comment by awkawk** [comment] 2015-08-17 12:37
Closing as a duplicate of ￼https://github.com/w3c/wcag/issues/111

**Closed by awkawk** 2015-08-17 12:37 UTC
Labels: General, Technical (bug)
