### ISSUE TITLE
links broken 2.5.3: Label in Name | single Vs. plural

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#745] opened 2019-05-20 07:12 UTC
The definition links are broken for:

https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html

They are single and need to be plural

**Comment by alastc** [comment] 2019-05-23 09:38
I think this is a build-process thing, an you confirm @michael-n-cooper ?

**Comment by awkawk** [comment] 2019-05-23 12:40
Duplicate of https://github.com/w3c/wcag/issues/465

**Closed by awkawk** 2019-05-23 12:40 UTC
Labels: Technical (bug), duplicate
