### ISSUE TITLE
anchor IDs do not match between definition links (in Understanding doc) and definition anchors

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#841] opened 2019-07-29 16:00 UTC
In the Character Keys Understanding document, in the third bullet of the SC text, the link to the definition of user interfact component links to 
> https://www.w3.org/TR/WCAG21/#dfn-user-interface-component

However, in the normative glossary, although the entry is singular, the anchor for it is plural, so the user is not positioned to the definition when it is activated.
> dfn data-lt="user interface components|user interface component" data-dfn-type="dfn" id="dfn-user-interface-components"

The link is correct in the normative language of the Character key Shortcuts SC in the standard, so this only appears to occur in the Understanding document. I would have thought the SC text in the Understanding documents was generated; however, there are other occurrences of the same issue. @michael-n-cooper , is there a way this can be corrected without user intervention?

**Comment by awkawk** [comment] 2019-07-29 17:59
Closing as a duplicate of https://github.com/w3c/wcag/issues/328

**Closed by awkawk** 2019-07-29 17:59 UTC

**Comment by mbgower** [comment] 2019-07-29 23:17
BTW, just had a look at the Understanding doc source and the SC text _is_ generated. So I cannot manually correct this.
