### ISSUE TITLE
No sufficient techniques listed for situation B

### ISSUE THREAD

**Issue by joshueoconnor** [w3c/wcag#104] opened 2015-06-26 08:27 UTC
https://lists.w3.org/Archives/Public/public-comments-wcag20/2015Jun/0003.html

Name: Jan Milde
Email: jmilde@opentext.com
Affiliation: 
Document: QR
Item Number: Success Criterion 4.1.2
Part of Item: 
Comment Type: editorial
Summary of Issue: No sufficient techniques listed for situation B
Comment (Including rationale for any proposed change):
In the document it says:
"Situation B: If using script or code to re-purpose a standard user interface component in a markup language:
Exposing the names and roles, allowing user-settable properties to be directly set, and providing notification of changes using one of the following techniques:"

Then, obviously a list of techniques should follow, but the list is empty.

Note: In "Understanding Success Criterion 4.1.2" at least there is one entry in that list. I assume there are supposed to be more than one entry.

**Comment by joshueoconnor** [comment] 2015-06-26 08:28
related to #103

**Comment by michael-n-cooper** [comment] 2015-07-07 15:40
Duplicate of #103

**Closed by michael-n-cooper** 2015-07-07 15:40 UTC
Labels: Editorial
