### ISSUE TITLE
"changes of context" definition complete?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#737] opened 2019-05-17 13:28 UTC
When reading the  "changes of context" definition I see:

https://www.w3.org/TR/WCAG21/#dfn-change-of-context

> major changes in the content of the Web page that...

This specifically talks only about "changes in the content of the Web page" not about moving away from the Web page.

Next I see:

> Changes in context include changes of:
> - user agent;
> - ...

Now I wonder what / how to understand this is perspective of the definition sentence.

Changes in user agent:

1. Is this leaving a specific UA and opening another UA? Is this possible? Is this even regarded as "changes in the content of the Web page"?
2. Is this the opening of another tab / window in the same UA? And is this regarded as "changes in the content of the Web page"?

OR:

Do we need to add this as part of the "changes of context" definition and need to extend the text?

**Comment by jake-abma** [comment] 2019-05-17 13:41
Like: "major changes in the content of the Web page, or leaving the Web page completely, that, if made without user awareness... "

**Comment by mraccess77** [comment] 2019-05-17 14:14
A change in viewport would be a new browser window or tab and viewports are listed as changes of context.

**Comment by awkawk** [comment] 2019-05-17 14:58
This is clarified in the note: Opening a new window, moving focus to a different component, going to a new page (including anything that would look to a user as if they had moved to a new page) or significantly re-arranging the content of a page are examples of changes of context.

**Comment by jake-abma** [comment] 2019-05-17 15:38
@awkawk 

> This is clarified in the note: Opening a new window, ...

Yes I've seen the note but that's exactly my point here, the text "changes in the content of the Web page" doesn't cover these scenario's as there may be no changes in the content and thus we have a mismatch, needing a note to explain we also mean other things.

The note should match scenarios of the definition text, right?

**Comment by awkawk** [comment] 2019-05-17 16:01
@jake-abma I think that it makes more sense when you see the connection to "web page"

**changes of context**
major changes in the content of the Web page that, if made without user awareness, can disorient users who are not able to view the entire page simultaneously

Changes in context include changes of:

- user agent;
- viewport;
- focus;
- content that changes the meaning of the Web page

Web page
a non-embedded resource obtained from a single URI using HTTP plus any other resources that are used in the rendering or intended to be rendered together with it by a user agent

**Comment by jake-abma** [comment] 2019-05-17 16:16
still the same... :-)  it's about:

"major changes in the content of a non-embedded resource obtained from a single URI using HTTP plus any other resources that are used in the rendering or intended to be rendered together with it by a user agent

Not: leaving the content intact and opening other screens.

Next is says "Changes in context" not "Changes of context" (if that matters...)

So, changes in context include changes of user agent:

- Is this leaving a specific UA and opening another UA? Is this possible? Is this even regarded as "changes in the content of the Web page"?

or

- Is this the opening of another tab / window in the same UA? And is this regarded as "changes in the content of the Web page"?

But the main issues here for me was the scope of the "content" change (not context change)

**Comment by jake-abma** [comment] 2019-05-17 16:42
Hi @mraccess77 in the context of "Changes in context include changes of viewport" I don't see any problems. Changes of User Agent is the one I would like to see some examples of. A native app opening a browser will do the trick but we're not focusing on native, only web.

**Comment by mraccess77** [comment] 2019-05-17 20:24
Perhaps a change of user agent might be an extension or platform level control taking over such as a platform video player, Flash player, etc.   In today's world we likely see less of this then we did in 2008.

**Comment by patrickhlauke** [comment] 2019-05-19 11:45
unexpectedly opening word/excel when clicking a harmless-looking link or button, perhaps?

**Comment by patrickhlauke** [comment] 2019-05-19 11:51
> @jake-abma I think that it makes more sense when you see the connection to "web page"
> 
> **changes of context**
> major changes in the content of the Web page that, if made without user awareness, can disorient users who are not able to view the entire page simultaneously
> 
> Changes in context include changes of:
> 
> * user agent;
> * viewport;
> * focus;
> * content that changes the meaning of the Web page
> 
> Web page
> a non-embedded resource obtained from a single URI using HTTP plus any other resources that are used in the rendering or intended to be rendered together with it by a user agent

I'd say it's more about either change of content of the current page, AND/OR about changing where the user ends up (if they're being shuffled to a new window, viewport, or just focus-yanked to a different part of the current page) without expecting it

so perhaps more along the lines of (written out far more verbosely than needed, but for clarity):

> **changes of context**
> major changes in either the content of the current Web page, or a complete change of where the user is currently focused/the current logical window they're operating in, that, if made without user awareness, can disorient users.
> 
> Changes in context include changes of:
> 
> * user agent (if a completely separate user agent, such as an external viewer programme, is opened);
> * viewport (if a new window is opened);
> * focus (if the user's focus is moved unexpectedly to a different part of the current Web page);
> * content that changes the meaning of the Web page

**Comment by jake-abma** [comment] 2019-05-19 12:18
@patrickhlauke thanks, and yes, Web browsers, media players, plug-ins, and other programs — including assistive technologies = UA so enough examples we can think of.

About your suggestion, that's exactly my point and I do like the way you set it up. Make it more clear.

**Comment by patrickhlauke** [comment] 2020-12-26 16:08
https://github.com/w3c/wcag/pull/1026 would be a nice addition/clarification here

**Comment by jake-abma** [comment] 2021-01-17 09:38
eager to see this on the agenda for discussion...

**Comment by patrickhlauke** [comment] 2021-01-17 09:41
+1

**Comment by mbgower** [comment] 2021-04-13 16:18
@jake-abma what about  just removing "in the content of" and changing it to "to" in the preamble to read:

> major changes to the web page that, if made without user awareness, can disorient users who are not able to view the entire page simultaneously

**Comment by alastc** [comment] 2021-04-13 16:21
Update from the meeting today: We couldn't get consensus on the PR, it is quite a big change that potentially changes conformance.

However, we could explore a smaller errata, e.g. starting the SC with "Major changes to the web page that, if made without user awareness.."

**Comment by mbgower** [comment] 2021-04-23 13:36
@jake-abma Please look at https://github.com/w3c/wcag/pull/1765

Based on the [group discussion](https://www.w3.org/2021/04/13-ag-minutes.html), there is significant opposition to substantial changes to the Changes of context definition. However, this very small change addresses your core concern:
> This specifically talks only about "changes in the content of the Web page" not about moving away from the Web page

Please let me know if this change would somewhat achieve your goal of clarifying the definition.

**Comment by patrickhlauke** [comment] 2021-04-24 09:20
I think the awkwardness of wording in this is more fundamental. Even looking at the case of focus change - philosophically a change of *focus* isn't a "change to the content of a web page", or a "change to the web page" (per @mbgower's suggestion) ... the page is still the same, just that the user's focus has been shunted around.

Maybe more fundamentally, this could do with modifying the starting sentence of the definition from "major changes in the content of the Web page that, if made without user awareness..." to just "changes that, if made without user awareness..." (and it then goes on to list the types of changes - user agent, focus, etc)

**Comment by alastc** [comment] 2021-09-03 15:41
Note to self for next time it comes up: We discussed the bigger changes, but Michael created a PR for a smaller change to bring forward.

**Comment by detlevhfischer** [comment] 2022-01-11 13:09
Incidentally, I take it that when the filtering of search results on a page triggers a reload of the same page (focus now on top of page) this is a change of context, not just content (implying that there is no requirement to communicate the changed number of entries via role=status to meet 4.1.3? Am I right?

**Comment by alastc** [comment] 2022-01-11 14:00
If there were a status message, e.g. "Showing 240 results" which changed, that would trigger 4.1.3, but otherwise not. I don't think the definition we're discussing impacts 4.1.3, as it is the status message that defines the scope.

**Comment by detlevhfischer** [comment] 2022-01-11 14:15
@alastc Well if you have a page loaded and the content of the container with role=status updates on that loaded page, you get an SR output, but if the entire page reloads, that'not possible (or not straightforward)? So I see a connection (but admittedly it's more a question about the applicability of 4.1.3 when page relaods occur).

**Comment by patrickhlauke** [comment] 2022-01-11 14:44
4.1.3 only applies to dynamic changes of content on the current page (though this is probably not super explicit in the normative wording). hinges on the definition of status message https://www.w3.org/TR/WCAG21/#dfn-status-messages - there's no "change of content without a change of context" if the whole page reloads.

**Comment by alastc** [comment] 2022-02-01 18:06
This was discussed again, we have a general desire to fix the definition but concerns about how and about current wording.  Possible way forward is to make a change that does not change the meaning and use errata to fix previous versions.

During the discussion I appreciated @GreggVan's point that it is the page which is conforming, so the change would have to be triggered by the page.

How about a one-word errata to make the examples clearer?

> major changes **triggered** by the content of the <a>Web page</a> that, if made without user awareness, can disorient users who are not able to view the entire page simultaneously

**Comment by mraccess77** [comment] 2022-02-01 18:18
I think this goes beyond just impacting those who can't view the entire page simultaneously - although that's an import aspect.

**Comment by patrickhlauke** [comment] 2022-02-01 18:30
are changes "triggered by the content of the Web page", or "triggered by the user interacting with the content of the Web page", or both? this seems an odd choice of words either way. it doesn't really matter who/what triggered the changes, or am i missing something? either way it's dynamic changes to the content

**Comment by bruce-usab** [comment] 2022-02-01 19:59
Adding a word (e.g., triggered) is narrowing the applicability, so I don't think that is quite what we are looking for.  I am sorry to say I could not follow the discussion today as closely as I would have liked.  I re-read this thread and checked the minutes, and am still not clear on the conflict.

Where are the examples some think go beyond the literal scope of the current SC or definition?

**Comment by alastc** [comment] 2022-02-01 21:58
@bruce-usab the summary is that the definition of "Changes of context" starts with "major **changes in the content of the Web page** that..." and follows up with examples that include changes of user agent, viewport, and focus.

Changing user agent (e.g. opening a PDF in another application), and changing the focus without changing the content do not match "changes in the content of the web page".

However, it would be a page that you are testing for conformance, so what I was trying to get at was that the issue must be on the original page. E.g. a link to a PDF, or a change of focus that doesn't update the page content.

Open to other suggestions, I'd like to re-visit next week whilst it is in people's recent memory.

**Comment by mraccess77** [comment] 2022-02-01 22:28
If the page you are on changes the context by opening a new window then the page is causing the issue although it appears to be a user agent change - and focus is moved away from the page - it is still caused by the original page.

**Comment by patrickhlauke** [comment] 2022-02-01 23:49
i'd still go back to either removing words and ending up with "changes that, if made without user awareness..." (per https://github.com/w3c/wcag/issues/737#issuecomment-826063500) or actually expanding it to "changes of content on the current web page, or changes of focus, that, if made without user awareness..."

unless this is deemed too much of a change? the latter would at least be much more upfront and explicit, without the need to then further clarify what the cryptic language of the definition (which is supposed to provide clarity) means

**Comment by patrickhlauke** [comment] 2022-02-02 00:01
it's an erratum either way (whether just one word, or a few words). and i would say the "change triggered by the content of the web page" introduces many unintended connotations (to me at least, "triggered by the content" sounds like it *only* covers things that happen automatically/on a timer, rather than as a result of user interaction) which may be more confusing in the end

**Comment by bruce-usab** [comment] 2022-02-02 00:15
I agree with an erratum.  But it seems like content/page/viewport all have the same self-referential enigma.

How about "major changes in the content of the Web page that" -> "change in presentation that"

**Comment by mraccess77** [comment] 2022-02-02 00:35
Hi @alastc I wasn't sure - so I was stating what I thought - if that aligns with what you are saying then that is good!

**Comment by alastc** [comment] 2022-02-02 09:12
> the dilemma I see is that changes of URI (or UA) are not literally "changes in the content of the Web page" because (per our definition) a change of URI is a wholly different Web page.

Indeed, but those changes would be triggered in the page being evaluated, which is where I was going.

My preference would be the current PR, but I was looking for something that would get through.

**Comment by patrickhlauke** [comment] 2022-02-02 09:51
was/is there pushback on just changing it to "changes that...", and then going on to bullet-list the types of changes? or any chance to just ask again how folks would feel about *that* as a compromise (simplifying that sentence, rather than trying to fix it by making it more obscure/hard to grok)

**Comment by bruce-usab** [comment] 2022-02-02 15:19
> those changes would be triggered in the page being evaluated

Agreed, and I don't think that this a problem with the current normative phrasing as it is understood.  Yes, my take away from the live conversation yesterday was that there is (legitimate) concern if the conformance status of the current Web page (i.e., the unit of conformance) is dependent on a wholly different Web page.

I agree that this sort of linkage could/would be problematic for an SC.  But we are talking about about a glossary term, and I am not understanding how it might be problematic for "change of context" to include URI switches.

It is possible that people have, all these years, been reading "of the Web page" as "or the Web page".  It is just a typo.

**Comment by patrickhlauke** [comment] 2022-02-02 15:54
> See the end of the minutes

frankly, I see a lot of misunderstanding and talking across purposes / not quite understanding what the proposed change even is/was. but whatever...so much stop energy that can probably best be used elsewhere. i guess i can live with changing

`major changes in the content of the Web page` to `major changes triggered by the content of the Web page`

as clunky, awkward, and cryptic as that sounds in the end. it's at least marginally closer to what the actual intent of the definition was/what it wanted to cover...

**Comment by bruce-usab** [comment] 2022-02-02 16:00
> frankly, I see a lot of misunderstanding and talking across purposes / not quite understanding what the proposed change even is/was

Yes, exactly.

**Comment by patrickhlauke** [comment] 2022-02-03 12:16
incidentally, i also don't quite get what the fear is with adding some extra clarification to the bullet points in the definition, as proposed earlier in the thread

> user agent (if a completely separate user agent, such as an external viewer programme, is opened);
viewport (if a new window is opened);
focus (if the user's focus is moved unexpectedly to a different part of the current Web page);
content that changes the meaning of the Web page

as i don't think that introduces any unintended/new interpretations, but just makes it more immediately understandable (which, one would think, is the point of a glossary definition)

**Comment by GreggVan** [comment] 2022-02-03 15:49
I think this is great.  Many people don’t know what we mean by many of these words (at all - or in that context).  This type of additional information makes it much friendlier for all - and understandable for the first time by some  (many?)

gregg

———————————
Professor, University of Maryland, College Park
Founder and Director Emeritus , Trace R&D Center, UMD
Co-Founder Raising the Floor. http://raisingthefloor.org
The Global Public Inclusive Infrastructure (GPII) http://GPII.net
The Morphic project  https://morphic.org

**Comment by patrickhlauke** [comment] 2022-02-03 16:23
so, as @GreggVan was (at least from what I can glean from the minutes of the call the other day) not a fan of changes originally, but now seems to have come around ... does this need *another* SC that folks should strawpoll on at the next meeting? I think there's been some talking across purposes/confusion in the actual call about what was actually being proposed/discussed...

**Comment by alastc** [comment] 2022-02-03 18:36
Ok, I've tried to construct a survey question which puts the context and options down as clearly as I can: https://www.w3.org/2002/09/wbs/35422/wcag22-misc/

**Comment by patrickhlauke** [comment] 2022-02-03 19:04
@alastc to nitpick, but absolute clarity - in the survey question, you have " and then has examples which are not conventionally thought of as changes of content". I think that should read " and then has examples which are not conventionally thought of as changes of context".

**Comment by patrickhlauke** [comment] 2022-02-03 19:05
(never mind, I misread...sorry for the noise)

**Comment by bruce-usab** [comment] 2022-02-03 19:10
I will suggest an option 0 -- change "of" to "to" and option 5 for something else.

**Comment by patrickhlauke** [comment] 2022-02-03 19:12
> I will suggest an option 0 -- change "of" to "to" 

but Bruce, *that* then still makes no sense, as "change to the content of Web page" does then still not cover changes in focus, or changes of user agent (e.g. opening a standalone PDF reader or Word or something), that is listed as an example of change of context...

**Comment by bruce-usab** [comment] 2022-02-03 19:14
Sorry, meant change "of" to "or"

**Comment by patrickhlauke** [comment] 2022-02-03 19:15
"or" still wouldn't cover the user agent example

**Comment by bruce-usab** [comment] 2022-02-03 19:16
A different UA is a different web page.

**Comment by bruce-usab** [comment] 2022-02-03 19:30
> and then has examples which are not conventionally thought of as changes of content

True.  Of the four item listed, only the last is (conventionally) a change of content.  The first is a switching UA, and with the second (viewport) and third (focus) there might not be a change in content.

The grammatical problem by my reading:
1. Changing to a different web page is not in the list.
2. Changing to a different web page is not a change in the content **_of_ the [current] web page**.

Both of those are resolved by changing "of" to "or".  One letter errata!

**Comment by patrickhlauke** [comment] 2022-02-03 19:42
"major changes in the content **or** the Web page" also wouldn't cover changes of focus (e.g. jumping to a different part of the current page, for instance) which *are* changes of context, which we're trying to define here

so as tempting as a "one letter errata" is...that ain't it.

**Comment by patrickhlauke** [comment] 2022-02-03 20:20
not really a grammar pretzel, but a logic pretzel. defines change of *context* as if it was a just about changes of *content*, but then lists examples that are correctly, and as intended originally, more than just changes of *content*. In short, that first sentence is unambiguously wrong. Wondering if "yes, it's wrong, but has anybody ever noticed?" is not really an ideal line of reasoning. Because then we might as well call 2.0/2.1 perfect now, and stop trying to fix things.

**Comment by alastc** [comment] 2022-02-03 23:11
@patrickhlauke  - sorry, I added a new option 1 which puts your answers out by one place. If you don't get a chance to update it, I'll assume you'd answer option 1 no, and move the others down.

**Comment by patrickhlauke** [comment] 2022-02-03 23:52
@alastc fixed my answers to the survey accordingly

**Closed** 2022-03-18 17:44 UTC
Labels: Survey - Added, WCAG 2.1, Member Comment, ErratumRaised, WCAG 2.2
