### ISSUE TITLE
inconsistent anchors and pointers

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#622] opened 2019-02-15 17:57 UTC
I'm encountering a number of inconsistencies between the pointers on Understanding pages.

In some, there is a discrepancy with the actual anchors used in the standard.
https://www.w3.org/TR/WCAG21/#dfn-images-of-text is the anchor in the normative document; however  in https://www.w3.org/WAI/WCAG21/Understanding/images-of-text  it points to #dfn-image-of-text (note lack of "s")

I'm assuming that the TR will not change, and that this will be handled as an Understanding doc change, not a TR erratum.

Note, that there are a few of these odd balls that don't agree between singular and plural anchors and the definition name. The singular "Image of Text" would have suggested the anchor would also be singular. Elsewhere User Agent (singular) has a plural anchor, https://www.w3.org/TR/WCAG21/#dfn-user-agents -- which causes a broken in link in [Resize Text](https://www.w3.org/WAI/WCAG21/Understanding/resize-text)'s terms link which points to  https://www.w3.org/TR/WCAG21/#dfn-user-agent)

Other inconsistencies include [Non-Text-Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast), where the in-page anchor to the failure techniques is #failures while almost all other Understanding documents use just #failure . Since I am trying to link to these, it makes it hard to know whether this is an aberration that will be corrected (and I should use a pointer without the plural) or if consistency will be ignored in such cases and I should just assume that what is in place for non-normative references is now stable.

**Comment by mbgower** [comment] 2019-02-15 18:06
@michael-n-cooper I'm assuming this is something you'll make a decision on.

**Comment by awkawk** [comment] 2019-02-15 18:09
Closing as duplicate of https://github.com/w3c/wcag/issues/594

**Closed by awkawk** 2019-02-15 18:09 UTC
Labels: duplicate

**Comment by mbgower** [comment] 2019-02-15 18:33
Okay, so based on Michael's response to the other issue
> I consider the respec change a regression but it's in the WCAG 2.1 Recommendation, so will have to sort out what to do for our xrefs in the generator.

The action that is going to result is still a bit confusing as the links occur in the normative SC text as links. So something which is now normative will be changed, right?  I'll assume, given the way Michael has phrased this, that the targets in the glossary will remain.

Note that #594 doesn't address the use of "failures" in the non-text-contrast Understanding, but I'll just consider that an abberration unless I hear differently.

**Comment by michael-n-cooper** [comment] 2019-02-26 23:34
The "failures" id was an editorial error, I just pushed a fix. The other issues are related to the problem described in #594, for which I may need to create a temporary fix and a different long-term fix.
