### ISSUE TITLE
2.4.7 Focus Visible verbiage

### ISSUE THREAD

**Issue by chlane** [w3c/wcag#1587] opened 2021-01-13 17:25 UTC
As an Accessibility Engineer I am trying to prevent developers from implementing low contrast focus indication. Some developers I am trying guide are insisting that WCAG allows low contrast visual focus indication as long as it is 2px wide. They are using verbiage from G195 to support their case. More details can be found at https://github.com/w3c/wcag/issues/1586. I'm hoping to get some form of official support for my opinion that they should provide 3:1 contrast for any visual focus indication regardless of pixel width.

**Comment by alastc** [comment] 2021-01-13 20:44
Hi @chlane,

We have some versioning going on here, where in WCAG 2.0 'focus visible' doesn't define what visibility is, so there needs to be something.

In WCAG 2.1 non-text contrast was introduced, and if the indicator is around the control, it needs to contrast with the background (outside the control). There isn't a requirement to contrast with the control though.

In WCAG 2.2 we have a potential criterion which defines the visibility. G195 was updated to be sufficient for the new criterion, but from the other issue we'll take a look at that if it is misunderstood.

**Comment by alastc** [comment] 2021-01-13 21:49
It seems this is a duplicate of 1588, I'll put my comment there.

**Closed by alastc** 2021-01-13 21:49 UTC
Labels: 2.4.7 Focus Visible
