### ISSUE TITLE
fix link to Input Purposes for user interface components section

### ISSUE THREAD

**Issue by robfentress** [w3c/wcag#3022] opened 2023-02-13 14:40 UTC
The link to [Input Purposes for user interface components section](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose#input-purposes) on the[ Understanding SC 1.3.5](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose) now just points to a non-existent ID, whereas before it took you to a page that had a list of valid input tokens.

**Comment by alastc** [comment] 2023-02-14 10:59
This is a duplicate of #2962, so closing.

**Closed by alastc** 2023-02-14 10:59 UTC
Labels: Duplicate
