### ISSUE TITLE
F17 being removed has left gaps in WCAG rules

### ISSUE THREAD

**Issue by jribbens** [w3c/wcag#1491] opened 2020-10-29 11:44 UTC
F17 was removed because F77 overlapped with it. However F17 included 4 tests, and only 1 of these overlapped with F77, so its removal lost 3 important tests that still need to be covered by WCAG (non-unique accesskeys, and various types of references to IDs where the ID does not exist). F17 should be reinstated (perhaps with its test 1 removed).

**Comment by patrickhlauke** [comment] 2020-10-29 11:52
duplicate of https://github.com/w3c/wcag/issues/1492

**Closed by patrickhlauke** 2020-10-29 11:52 UTC

**Comment by jribbens** [comment] 2020-10-29 12:05
Apologies, no idea how this duplicate happened - github responded with a 404 error page the first time I opened it (!)

**Comment by patrickhlauke** [comment] 2020-11-04 08:10
hey, no biggie. sometimes our tools fail us :)
