### ISSUE TITLE
Can we get a better example?

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#2755] opened 2022-10-28 21:41 UTC
During a review of the [Understanding document](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html), it was pointed out that the Figure 9 diagram on a hypothetical arrangement of 5 buttons in a cross, was not the best set of examples on  the advantages of the criterion, since it was difficult to understand how the second example, where the middle target is reduced in size to 10x10, but the spacing is maintained for the other 4 targets, is really more difficult to operate than the first example, where it is in the same position at 24x24.
![image](https://user-images.githubusercontent.com/14298245/198733034-1285a0d8-d945-4dfd-9ec7-094489eb27af.png)

Someone argued that there is no higher likelihood of the user mis-pressing the center control in the second example than the first, and in fact in the second one, the reduced size of the target may result in less  presses of the neighbouring controls.

One could argue that the example illustrates some of the curiosities of the measuring outcomes. Is it better to remove it, or to explain more fully what makes B a failure?

**Comment by patrickhlauke** [comment] 2022-10-29 06:34
I intended that figure to be an example of the curious aspects/ side effects of the SC ... so I'd be in favour of keeping it and explaining it furtherOn 28 Oct 2022, at 23:41, Mike Gower ***@***.***> wrote:﻿
During a review, it was pointed out that the Figure 9 diagram on a hypothetical arrangement of 5 buttons in a cross, was not the best set of examples on  the advantages of the criterion, since it was difficult to understand how the second example, where the middle target is reduced in size to 10x10, but the spacing is maintained for the other 4 targets, is really more difficult to operate than the first example, where it is in the same position at 24x24.

Someone argued that there is no higher likelihood of the user mis-pressing the center control in the second example than the first, and in fact in the second one, the reduced size of the target may result in less  presses of the neighbouring controls.
One could argue that the example illustrates some of the curiosities of the measuring outcomes. Is it better to remove it, or to explain more fully what makes B a failure?

**Comment by GreggVan** [comment] 2022-10-29 20:31
Yes - can someone explain again (or point to the explanation) of how 1 passes but 2 fails? 

gregg

------------------------------
Gregg Vanderheiden
***@***.***

**Comment by patrickhlauke** [comment] 2022-10-30 00:21
On 29/10/2022 21:31, Gregg Vanderheiden wrote:
> Yes - can someone explain again (or point to the explanation) of how 1 
> passes but 2 fails?

Just measure it. When the controls are all touching, the central one has 
a width/height of 24x24 CSS px. when they're not, and you calculate the 
offset (let's just stick to horizontal or vertical, not diagonal), 
you'll see that in figure two the offset is 10 CSS px + 7 CSS px = 17 
CSS px, so below 24 CSS px. so for adjacent targets like that, the 
smaller the actual target, the more the spacing needs to "telescope" out 
to then get to the 24 CSS px offset.

P
-- 
Patrick H. Lauke

https://www.splintered.co.uk/ | https://github.com/patrickhlauke
https://flickr.com/photos/redux/ | https://www.deviantart.com/redux
twitter: @patrick_h_lauke | skype: patrick_h_lauke

**Comment by patrickhlauke** [comment] 2022-10-30 00:25
btw agree that in practice, 2 is no more difficult to operate than 1. but this example illustrates that following the actual wording of the SC can (as is often the case) result in counterintuitive edge cases. I think we are agreed that 2 fails, and the failure is not a "real-world" failure, but strictly a "going by the wording/calculations" failure

**Comment by bruce-usab** [comment] 2022-10-30 18:52
I don't think we should keep this illustration (figure 9) as-is, at least not the left most one.  It is comparing the base requirement (24x24) to the exception, so that is not actually useful to do.

I would change the middle illustration to shrink the outer squares to 10x10 and float them towards center, so all five targets are  the same size.  That illustrates why it is a fail.

The actual problem with the left most is illustration is that it is malicious compliance.  Someone who has significant difficulty hitting a 24x24 target reliably, and is trying to hit the middle of the five, will hit one of the other four more often than not.

Illustrations of the exceptions are fine.  Just don't compare them to 24x24 requirement -- unless it helps with understanding.

In Understanding, we try to avoid examples which are terrible but just-barely technically conformant.  That leftmost illustration is a UI nightmare for someone with fat fingers and tremors.  Please do not include it.

**Comment by yatil** [comment] 2022-10-30 20:22
Without this image, I would not have thought of the number 2 use case. So I would strongly support keeping the illustration.

**Comment by GreggVan** [comment] 2022-10-30 20:23
I concur

If there are images that point out complexity - we should not remove them to make it seem simpler than it is.

gregg

———————————
Professor, University of Maryland, College Park
Founder and Director Emeritus , Trace R&D Center, UMD
Co-Founder Raising the Floor. http://raisingthefloor.org
The Global Public Inclusive Infrastructure (GPII) http://GPII.net
The Morphic project  https://morphic.org

**Comment by patrickhlauke** [comment] 2022-10-30 21:36
> The actual problem with the left most is illustration is that it is malicious compliance. 

how is it malicious? it does EXACTLY what the SC says...that the minimum is 24x24 CSS px.

> Someone who has significant difficulty hitting a 24x24 target reliably

...is not well served by this SC.

> In Understanding, we try to avoid examples which are terrible but just barely technically conformant. That leftmost illustration is a UI nightmare for someone with fat fingers and tremors. Please do not include it.

I disagree. the example on the left is EXACTLY what the minimum for this SC is. if you're arguing that it's a bad minimum, then there's a problem with the SC, not with the example that illustrates it.

**Comment by bruce-usab** [comment] 2022-10-31 13:19
You are correct @patrickhlauke that the left figure is not malicious.  It has been constructive for our conversations.  Regardless, I am of the opinion it is counterproductive to include in Understanding.  It is not surprising that there would be discontinuity between the basic requirement and a mathematically stricter exception.

This SC is aimed at PWD with fine motor difficulties, and IMHO a significant population will be well served by its inclusion (as compared to having nothing similar under 2.0 Level AA).  I am _not_ arguing that 24x24 to be a bad minimum.  For A/AA, it pretty good, and (very close to) the most we can get.

I like the middle use case.  The **middle example has terrible usability** and this SC correctly catches and fails it.  I agree the middle example has better usability than the left one, but I do not find that anything more than a curiosity.  There are a number of barely-passes red herrings that have worse usability than barely-fails examples.

**Comment by GreggVan** [comment] 2022-10-31 15:56
hmmm

If using your finger - the middle one is actually better than left one

If using a mouse - the left one is far superior.   
	(Interestingly the left one with a small dot in the middle  (that can’t be confused as a target but does mark the center of the square)  is even better)

The right one is best for finger and worst for mouse
The left one is best for mouse. And worst for finger

So which one is best?     

I still don’t understand why the middle one fails?
(don’t tell me that’s the way it is written.  My question is - why is it written that way? ) 
  (Why have we constructed the SC such that middle one fails when left and right pass)


Thanks 

gregg

———————————
Professor, University of Maryland, College Park
Founder and Director Emeritus , Trace R&D Center, UMD
Co-Founder Raising the Floor. http://raisingthefloor.org
The Global Public Inclusive Infrastructure (GPII) http://GPII.net
The Morphic project  https://morphic.org

**Comment by mbgower** [comment] 2022-10-31 22:45
Realizing that _any_ policy is going to create borderline pass/fail where you have this discussion (why is 30mph any safer than 31mph, etc), here is how I replied to the person on my team who raised this...

> 1. The first situation is a minimum pass. No padding around the items. Despite that, there’s pretty good affordance for the outside four (if you click near the outside edge) but a higher chance of fat fingering the middle one.
> 1. The second situation, there’s no improvement in preventing user error on the middle one AND it becomes more difficult to hit the middle target. For someone with reduced fine motor control, they are more likely to land 'between' the targets and have to press again. In any repeated action, the odds of someone accidentally triggering the other components goes up, especially if they have operational difficulty (through tremors of whatever). That's simple probability.
> 1. In the third case, the smaller target has more space around it, so the chance of accidental triggering the surrounding items while trying to hit the smaller middle target goes down. 

>I don’t think anyone would dispute that the third is better than the second?  Obviously all 5 targets at 24x24 AND space between them would be better still!
They could probably make it clearer that this is a borderline case than just saying “(hypothetical)“, but I do think it’s defensible from this point of view.

**Comment by mbgower** [comment] 2022-11-01 00:31
> If using your finger - the middle one is actually better than left one

> The right one is best for finger and worst for mouse
The left one is best for mouse. And worst for finger

@GreggVan can you explain how you reached those conclusions?

**Comment by GreggVan** [comment] 2022-11-01 02:05
From human factors research with finger operated buttons.


Think of how accurate your finger has to be to not touch the next button. 

If you have buttons that are    2 cm square and spaced 4 cm center to center)   - and your finger is 2 cm round - you need to his the exact center of the button to not touch the next
And if you have a fat finger (more that 2 cm) you are in trouble.
(Now your finger is a bit pliant at the edge so… if the buttons don’t go down far you have a little more leeway - but you get the drift. 

If you have  1 cm square buttons  (still spaced 4 CM center to center    NOW  you have 3 CM for your 2 cm finger to roam around in before it will hit a neighboring key. And a fat finger will also work. 



This is completely different if you are using a pointer with an infinitely small point (  .1 mm finger)

NOW the bigger the button the more room you have to move around and the top 2 CM buttons are much easier to hit than then 1 cm button — and you don’t have to worry about your finger hitting the one next to it. (Unless you 1 CM off target and hit the next button with your needle finger) 


gregg

———————————
Professor, University of Maryland, College Park
Founder and Director Emeritus , Trace R&D Center, UMD
Co-Founder Raising the Floor. http://raisingthefloor.org
The Global Public Inclusive Infrastructure (GPII) http://GPII.net
The Morphic project  https://morphic.org

**Comment by GreggVan** [comment] 2022-11-01 02:09
I agree with this  - if you are talking about mouse pointer activation

If using fingers - then  a different analysis would be needed   (see other email)

What gets me is that we make content for use both with mouse and finger - and the better answer is not the same ….

**Comment by bruce-usab** [comment] 2022-11-01 10:57
> hmmm If using your finger - the middle one is actually better than left one 

I agree, and wrote as much.  (And others' comments note this apparent contraction as well) The problem is that (for fat fingers and/or tremors) the middle one is so very difficult to use.  It matters not at all that middle is a little better than left because it's just comparing something quite bad to something even worse.

> The right one is best for finger and worst for mouse

That is okay IMHO because that pattern is not difficult to operate with a mouse.

> Why have we constructed the SC such that middle one fails when left and right pass?

That is not deliberate, it follows because there is a discontinuity between the basic requirement (24x24) and the exception allowing smaller, so long as there is 24px target offset in every direction.  Some exceptions excuse poor a11y for good reason (e.g., essential).  The spacing exception provides for alternative designs (ones smaller than 24x24) but is slightly stricter.

It is to be expected that there would be a discrepancy between a requirement for minimum target size and an exception based on spacing (especially as spacing approaches the minimum allowed).  This is why I argue that it is of very little utility for Understanding to compare the base requirement to an an exception.  Illustrate the base requirement, fine.  Illustrated the exceptions, fine.  Illustrate the two next to each other, to what end?  Just to invite criticism?  Should Understanding have an illustration of text contrast showing 4.49:1 as compared to  4.51:1 ?

**Comment by patrickhlauke** [comment] 2022-11-01 11:03
> Just to invite criticism?

are you afraid of backlash against the actual wording of the SC and its exceptions? the diagram illustrates an actual reality of the SC. sweeping it under the carpet does not make it go away.

the point of the diagram is that ideally, you want 24x24. but knowing that if you do opt to make things smaller than that (as the SC explicitly allows), you need to account for the extra spacing/clearance. ideally, this will actually make designers/developers opt for the minimum 24x24 because it shows that with the extra clearance, you actually need to space things further apart overall than if you just followed the recommended 24x24 minimum.

**Comment by patrickhlauke** [comment] 2022-11-01 11:06
>  it is of very little utility for Understanding

the fact that some in this discussion right here didn't grok why the middle one is a failure to me illustrates *exactly* why this does have utility in the understanding, as it lays bare what is otherwise a hidden counterintuitive outcome of the SC

**Comment by bruce-usab** [comment] 2022-11-01 11:24
I am not afraid of backlash.  There has been plenty of that over the years.  It is okay.  It is not sweeping it under the carpet.  My concern is that Understanding should provide illumination, not reason to doubt that an SC is reasonable.

> the point of the diagram is that ideally, you want 24x24. but knowing that if you do opt to make things smaller than that (as the SC explicitly allows), you need to account for the extra spacing/clearance. ideally, this will actually make designers/developers opt for the minimum 24x24 because it shows that with the extra clearance, you actually need to space things further apart overall than if you just followed the recommended 24x24 minimum.

This would be an excellent lesson for Understanding!  I do not believe the present framing accomplishes that goal.

> the fact that some in this discussion right here didn't grok why the middle one is a failure to me illustrates exactly why this does have utility **in the understanding**

I agree that this discussion (and this particular illustration) is of great utility!  I disagree that we have distilled the lesson to incorporate into Understanding. 

> ...as it lays bare what is otherwise a hidden counterintuitive outcome of the SC

Again, I do not think that it is all that surprising that a measurement-based SC would not seamlessly align with an exception based on measuring something different.

Guidance that it is better to "design for target size rather than spacing" is a straightforward concept for Understanding.  Emphasizing how the SC misses/passes some bad target size patterns while catching/failing some-bad-but-not-as-bad spacing patterns is not constructive.

**Comment by patrickhlauke** [comment] 2022-11-01 11:30
emphasizing? aknowledging, more like. by not aknowledging it, you'll just end up with people "discovering" this on their own and writing lengthy blog posts about how WCAG is flawed (see for instance those blog posts about how the old colour contrast calculation is nonsensical in certain situations)

it could have been worse, it could have been a 1x1 CSS px button with 23 CSS px clearance around it that also passes.

**Comment by mbgower** [comment] 2022-11-01 14:05
> My concern is that Understanding should provide illumination, not reason to doubt that an SC is reasonable.

I see both your points here, but I tend to side with Bruce. The Understanding document should show good examples we want folks to emulate and demonstrate bad things we want folks to avoid.

It's okay to have a brief discussion on how edge cases may result in counter-intuitive/productive results, so long as it's made clear that a 'better-than-minimum pass' will result in a design that is clearly better. (For example, the five 24x24 targets, each with a bit of space between them, as in image C.)

As Bruce says, if our SCs on contrast focused on the borderline cases or some of the odd pass/fail examples listed in that huge discussion started by Andy, I don't think it would improve adoption. But a brief section on why _more_ than the minimums tends to be better would be okay.

**Comment by patrickhlauke** [comment] 2022-11-01 14:15
the examples (figure 8 and figure 9) are preceded by

> The aim of this Success Criterion is that targets are ideally at least 24 by 24 CSS pixels. However, the offset exception allows for smaller targets if there is sufficient spacing around them. Authors should be aware that using smaller targets can have an impact on layouts, as the combined space of the smaller target and the required spacing around it will generally require an overall area that is larger than 24 by 24 CSS pixels.

I'd be in favour of expanding this explanation (maybe even creating a new heading/section for this), stressing that it's not recommended to go below 24 by 24, but that IF authors must do it, then they need to be aware that they must provide further spacing/clearance as a result to remain compliant. And that yes, this can lead to edge cases (I didn't even show the 1x1 CSS px extreme case) that are not good for usability (which, if i recall correctly, at the time that this SC was devised were handwaved as "but nobody would do that anyway...")

**Comment by mbgower** [comment] 2022-11-01 14:18
It might also be helpful to show some the same thing 'at scale' (i.e., actually 24x24). The blown up example may be contributing to some confusion?

**Comment by patrickhlauke** [comment] 2022-11-01 14:23
Incidentally, figure 8 shows the comparison of 24x24 and 10x10 with extra spacing (without an in-between fail example). is THIS one of the causes of confusion, having the intermediate naive "just making the centre target smaller while keeping everything else in place" fail example? what about going straight from the left-most to the right-most examples?

**Comment by GreggVan** [comment] 2022-11-01 17:17
+1
gregg

**Comment by yatil** [comment] 2022-11-01 20:45
I think the Understanding should (if not must) show the edge cases, because the issue for testers is not when everything is clear. It is the edge cases that should have clear guidance and answers. It worries me that some people in the Working Group seem to not see the need to give testers clear information on how to check for a pass or fail. Sure, as an implementer, you should always use the best practice (technique), but due to WCAG being a guideline and an evaluation standard in unity, it’s essential to cover all use cases.

**Comment by detlevhfischer** [comment] 2022-11-02 06:23
The most important point for the understanding documents is explain how an SC apples to the common set of content elements as succinctly as possible. It would be good to show, for example, that you can have targets in a menu bar smaller than 24 x 24 px but that there are 'diminishing returns' in that with a reduced size you have a widening gap and less real estate for the actual icon image. 

I struggle to remember any actually implemented configuration the illustration above would be an example of. Such may exist, but it is fairly uncommon. Given that one could fill the Understanding text with edge cases aplenty, making for a rather unwieldy thing, I think we should value brevity above completeness. Authors using these documents have little time and patience with stuff that does not relate to their actual needs and questions. So while I find the graphic instructive and useful for honing our language (and possibly offering another test case for automatic measurement approaches - witness the separate discussion of including diagonals or just measuring horizontal/vertical, slanted targets, and the like) I would prefer more common examples in the understanding text.

**Comment by yatil** [comment] 2022-11-02 07:04
> I struggle to remember any actually implemented configuration the illustration above would be an example of. Such may exist, but it is fairly uncommon.

Literally any collection of social media icons on websites ever. Plus menu bars with icons like the one above the text field that I’m just typing into. 

> Given that one could fill the Understanding text with edge cases aplenty, making for a rather unwieldy thing, I think we should value brevity above completeness.

Every SC had an infinite number of edge cases, nobody asks about completeness. But there is a line when brevity means that it makes the document harder to understand. 

> As for the need of testers, I dearly hope we will eventually have some automatic testing algorhythm that does not leave too many edge cases to be sorted out manually...

Ah yes, the mythical automated testing algorithms that get created from the Understanding documents that do not explain any edge cases. And in the meantime, we put the burden on testers and volunteers explaining again and again the same concepts because the Understanding is not helping them at all. And all that while most people are distracted by WCAG 3. 

Take a look into the forums and see which questions come up. Which are repeated. The Understanding docs regularly fail at their job and the WG doesn’t even notice. And when people like Patrick give feedback, PRs even, they are ignored or take months to be adapted. I am actively telling people to not look too closely at the Understanding documents and ignore the Techniques because they are often useless. 

That said, this illustration does not hurt and highlights an interesting quirk of the SC, encouraging authors to increase their tab targets, especially if they need compact layouts. It is a good example.

**Comment by detlevhfischer** [comment] 2022-11-02 07:25
@yatil I do not specifically object to figure 9 remaining in the Understanding text - just making a general point about the usability of our documentation. Looking at the [2.5.8 Understanding text ](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html)again, it appears that it would benefit from having the graphics done in a consistent style and scale. I prefer the cleaner way fig. 8 and 9 are done to my own graphics (fig. 1-7). 

When I said the configuration in fig. 9 seemed uncommon, I was particularly referring to the second example in fig. 9 - the target in the middle with reduced size. As to social media icons, I cannot recall any where they are not basically lined up (as are the controls here in GitHub). 

The general point remains that there is a trade-off between succinctness and completeness. Perhaps there is a case for two types of understanding - the general one that shows the common cases, and an in-depth one that covers the many edge cases. These may be separate documents or just sections within one document.

**Comment by alastc** [comment] 2023-02-16 11:36
Going back to the original point, on another issue we added this after the example:
> The ability to select the central option is reduced in the second version, it is smaller (therefore harder to successfully hit) and there is little spacing around the target. In the third version the center target is still harder to hit, but it is less likely that you'd hit a neighboring target. The measure for target offset works intuitively for most cases, but in some cases, at small sizes, it can cause additional spacing to be required.

Is that sufficient for this?

**Comment by mbgower** [comment] 2023-02-16 14:31
@yatil 
> Plus menu bars with icons like the one above the text field that I’m just typing into.

All those buttons in the toolbar in Github are sufficient (including the Add Save Reply button on the end that has a smaller focus indicator). As well,  I feel like we have a clear examples of 4 configurations of a classic toolbar that illustrate such things. So I'm a little surprised to hear you say those are lacking?

The more interesting ones in the github editing interface for illustrative edge cases are actually the Markdown and expand text area buttons in the bottom right corner, for the following reasons:
1. they are potentially smaller
2. the markdown button collides with the large target for attaching files to its 'left' _and_ 'right' (it appears to be placed within the region of that larger hit area, except, curiously, at the top.
3. the expand text area 'button', which I think abuts both the scrollbar above AND the upper right corner of the Attach files region on the bottom (and although it is not relevant to this SC, like every other expand text area I've seen, has no apparent keyboard alternative/equivalent to the pointer mechanism)

One of the challenges when we're creating examples is that there is at least good etiquette (if not copyright) preventing us from pointing out poor (and for copyright, maybe even good) examples in the wild in our Understanding documents. So short of building a fairly elaborate example, some of the richer challenges are tough to illustrate without creating reams of content in the Understanding documents, which I fear we've achieved in some of our more elaborate 2.1 & 2.2 SCs.

> The Understanding docs regularly fail at their job and the WG doesn’t even notice. 

I wouldn't say that :) Likely more accurate to say that the same forces that make it hard to get traction on updating obvious typos and broken links in 2.0 material, also make it (much) harder to update the whole content management system for W3C. Sometimes I think folks believe there's a giant workforce behind this. Reality is, it's mainly driven by volunteers with day jobs. I hear and feel your pain!

@alastc
> Is that sufficient for this?

Earlier I said that I thought examples that are at scale may help. I continue to think so. Large illustrations can be useful, but I think especially for target size examples of small targets, it's helpful that if viewed at 100%, those target examples are at least roughly to scale?

**Comment by mbgower** [comment] 2023-02-16 14:49
@alastc
> Is that sufficient for this?

Earlier I said that I thought examples that are at scale may help. I continue to think so. Large illustrations can be useful, but I think especially for target size examples of small targets, it's helpful that if viewed at 100%, those target examples are at least roughly to scale?

For this set of examples, I also think a fourth one, which shows the same 5 targets with the spacing of the fourth but all targets at 24x24 would illustrate what I _hope_ is agreed to by all as the best outcome (i.e., minimum 24x24 with some spacing too). As I mentioned, if these were at roughly at 1:1 scale, I really feel like the illustrations would be easier to understand. 
PS I also like @patrickhlauke's longer explanation [earlier,](https://github.com/w3c/wcag/issues/2755#issuecomment-1298357717), as well as his summary a few comments later, and it may be worth pulling in some of [my earlier comments](https://github.com/w3c/wcag/issues/2755#issuecomment-1297781598) from before as well (assuming they are agreed with). The more explanation we have around this, the better.

**Comment by alastc** [comment] 2023-02-16 22:57
@mbgower - At that size they are hard to see (particularly the size labels), but Patrick suggested an SVG, I think that could be opened in a new tab and zoomed? 

The text I put in above is already merged, I think it says similar things to your comments, but open to suggested updates.

@patrickhlauke - sorry, I've replied on email, but yes, please do.

**Comment by mbgower** [comment] 2023-02-17 17:44
> At that size they are hard to see (particularly the size labels)  but Patrick suggested an SVG

Yeah, that is an option, as is having a large illustration to show measurement, etc., and then immediately following it with an example (using SVG?) at 1:1 scale

I'm hopeful that viewing the examples at real scale will better align everyone on interpretation and understanding.

**Comment by patrickhlauke** [comment] 2023-02-19 15:07
Working on these example images at the moment, and have a plan to make them clearer and reduce some redundancy with the Figure 1 (in short, redoing figure 1 as SVG and expanding it slightly, as it effectively conveys same/similar idea of figure 5 - may add a slightly more severe example at the end of it, but having it at scale may well put people off even more from taking that approach, which will serve the intended purpose of being a deterrent; and then redoing what is currently figure 6 as SVG, but moving it directly after figure 1, and changing the explanation/writeup to make the point even clearer). watch this space...

**Comment by patrickhlauke** [comment] 2023-02-24 00:28
@mbgower @alastc @detlevhfischer still want to tweak one of the illustrations a bit to make sure all the spacings between lines and labels etc are all correct and the same, but ... I have a draft change to the 2.5.8 understanding here https://github.com/w3c/wcag/pull/3058

**Comment by detlevhfischer** [comment] 2023-02-24 06:45
Well done  I am glad my original illustrations will be replaced with something cleaner. Now they show up the rest o the bitmap illustrations though :) I wish all were done in that neat way.
And there is at least one that's now clearly wrong: the numbered list marked as fail (because as it stands it would fall into the inline exception now)

**Comment by alastc** [comment] 2023-02-24 09:19
> And of those, there is at least one that's now clearly wrong: the numbered list marked as fail (because as it stands it would fall into the inline exception now)

Yep, I've removed that in a different PR.

**Comment by patrickhlauke** [comment] 2023-02-24 11:16
Quick question, as I'm confused now: looking at https://w3c.github.io/wcag/understanding/target-size-minimum.html i see the list examples and the (always slightly freaky to me) image with the magnifying glass and the boy/girl image aren't there anymore...but for some reason, they're still present in my PR. have I accidentally messed up the merge to bring my PR up to date with main? in short, is the version on https://w3c.github.io/wcag/understanding/target-size-minimum.html now the definitive one that my PR should be applied to (and I should remove the extraneous bits from the PR, which otherwise would reintroduce them)

**Comment by detlevhfischer** [comment] 2023-02-24 11:20
@patrickhlauke I think the sullen boy-girl example is still correct and should not be removed? (It might help to add a pass-example where the loup icon on top of the image is actually large enough (as this will be the most likely way to implement that kind of thing).)
@alastc Have you removed too much?

**Comment by patrickhlauke** [comment] 2023-02-24 11:23
also, happy to convert some more illustrations to cleaner SVG (though I did fuss over the two I made for ages, as I'm a perfectionist when it comes to alignments/distances/making sure the SVG when rasterised hits "full pixel" rather than "half pixel" coordinates). can do another pass once we've settled on exactly what should/shouldn't be in that understanding, per the above

**Comment by detlevhfischer** [comment] 2023-02-24 11:24
> also, happy to convert some more illustrations to cleaner SVG

That woud be great!

**Comment by patrickhlauke** [comment] 2023-02-24 11:26
the boy/girl example was removed here https://github.com/w3c/wcag/commit/9a9ddba57393c2c77bfb889c26680ac46f54b92d

**Comment by patrickhlauke** [comment] 2023-04-02 08:38
once we have clarity on which way we're taking Target Size spacing, i'll dedupe the two PRs with better examples etc

**Comment by alastc** [comment] 2023-04-18 15:17
> @patrickhlauke I think the sullen boy-girl example is still correct and should not be removed? ... @alastc Have you removed too much?

At the time I removed that it wasn't a useful example, but please take the latest SC text from:
https://github.com/w3c/wcag/pull/3123/files#diff-a30d6476d02e45a066c55e8e174fe5381088cb0a3862e9c2e4eb3bbdf695c007 

I'm just trying to get my head around the various PRs, is the intent to use #3103 and #3089 and drop #3058?

**Comment by patrickhlauke** [comment] 2023-04-18 18:05
> I'm just trying to get my head around the various PRs, is the intent to use #3103 and #3089 and drop #3058?

*IF* we're going with the new circle-based spacing proposed in #3123, then #3058 is obsolete (as it makes better examples for target offset), and we'll instead want to go with https://github.com/w3c/wcag/pull/3103

**Comment by patrickhlauke** [comment] 2023-05-03 15:58
Closed https://github.com/w3c/wcag/pull/3058 and this is now (with the change to spacing based on circles being merged) superseded by https://github.com/w3c/wcag/pull/3103

**Closed** 2023-05-09 15:44 UTC
Labels: Survey - Added, Understanding, WCAG 2.2, 2.5.8 Target Size (Minimum)
