### ISSUE TITLE
"Understanding" pages are missing a link back to the SC

### ISSUE THREAD

**Issue by mrtnmgs** [w3c/wcag#3640] opened 2024-01-17 14:10 UTC
Unless I missed it, the "Understanding" pages do not link back to the Success Criterion. 
For instance https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html
should have a link pointing to: https://www.w3.org/TR/WCAG22/#non-text-contrast
Based on my own experience it would be very useful ^^

It could be added in the nav banner, related resources section, or the part of the h1 mentioning the SC name (e.g. from
`<h1><span class="standalone-resource__type-of-guidance">Understanding SC 1.4.11:</span>Non-text Contrast (Level AA)</h1>` to `<h1><span class="standalone-resource__type-of-guidance">Understanding <a href="https://www.w3.org/TR/WCAG22/#non-text-contrast">SC 1.4.11</a>:</span><a href="https://www.w3.org/TR/WCAG22/#non-text-contrast">Non-text Contrast (Level AA)</a></h1>`

Happy to take care of the edit if I know the change will be approved...

**Comment by patrickhlauke** [comment] 2024-01-17 16:50
> Happy to take care of the edit if I know the change will be approved...

that's probably something that should be done throughout all understanding docs, not just this one. I have vague memories of this being discussed at some earlier point following the W3C site redesign /cc @iadawn

**Comment by mrtnmgs** [comment] 2024-01-17 18:07
yes, I can take care of editing all Understanding SC pages.

**Comment by JAWS-test** [comment] 2024-01-18 06:29
Duplicate of https://github.com/w3c/wcag/issues/2954

**Comment by iadawn** [comment] 2024-01-18 09:22
@mrtnmgs Let me take a look at it. There will likely be an easier way of doing it than editing every Understanding page.

**Comment by scottaohara** [comment] 2024-01-18 12:07
Along with the issue jaws test linked to, there is at least one or two other issues on this topic as well.  

Hard agree that this should be fixed asap

**Comment by patrickhlauke** [comment] 2024-01-18 12:47
> @mrtnmgs Let me take a look at it. There will likely be an easier way of doing it than editing every Understanding page.

exactly, something at site-generation/in the xsl templates would likely be more robust/fixing the problem at the core

**Closed** 2024-05-02 11:20 UTC
