### ISSUE TITLE
5.2.2 Full pages 3rd Note has redundant text "New" 

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#699] opened 2019-04-24 17:33 UTC
At https://www.w3.org/TR/WCAG21/#cc2 the third note starts with "New":

`<span class="change">New</span>`

Think this has been mentioned before but it's still here.

**Comment by awkawk** [comment] 2019-04-24 17:35
Duplicate of https://github.com/w3c/wcag/issues/413

**Closed by awkawk** 2019-04-24 17:35 UTC
Labels: duplicate
