### ISSUE TITLE
3.2.7 Hidden Controls – Proposed exceptions for skip links and any other control whose sole intention is to enhance the experience of keyboard users

### ISSUE THREAD

**Issue by CarynPagelTR** [w3c/wcag#1441] opened 2020-09-18 20:48 UTC
On Behalf of Thomson Reuters 

We don't believe it is the working group's intent to include controls whose sole intention is to enhance the experience of keyboard users in this Success Criterion. We propose making exceptions clear:  

- Skip links 
- Any other control whose sole intention is to enhance the experience of keyboard users

**Comment by wittjeff** [comment] 2020-09-18 23:20
+1

**Comment by innoticFR** [comment] 2021-02-01 16:37
In my opinion, having hidden skip links does not enhance the experience of keyboard users who do not use a screenreader. 

There are more users suffering motor impairments than blind users, and requiring the user to hit the tab key to know whether or not a skip link exists is a complex operation.

**Comment by CarynPagelTR** [comment] 2021-02-02 14:40
@innoticFR I definitely agree that visible skip links are easier to use than hidden ones. I should clarify by hidden skip links, I meant they still become visible upon receiving focus, but are initially hidden. Either way, the intent of this proposed SC "is to ensure that controls needed to progress or complete a process" so it may be implied that skip links are not included.

**Comment by innoticFR** [comment] 2021-02-02 14:56
I agree that "skip links" are not necessary to complete a process, so they are de facto excluded from this SC. I fear that making an explicit exception for "skip links" would legitimate what I personnaly consider a counterproductive idea.

This SC is exactly here to tell that requiring focusing a link to be visible is a bad idea, and why this is a bad idea.

A good alternative would be to explicitely state that although "skip links" are not directly covered by this SC, people are encouraged to make them always visible without requiring pointer hover or keyboard focus.

**Comment by CarynPagelTR** [comment] 2021-02-02 15:01
@innoticFR do you think 2.4.1 would be a better place for that encouragement?

**Comment by innoticFR** [comment] 2021-02-02 15:24
The sufficient [G1](https://www.w3.org/TR/WCAG20-TECHS/G1.html) technique for 2.4.1 already contains the following paragraph:
>Note: It is preferable for links to be visible at all times, since users navigating via the keyboard include switch users, those using techniques that generate keyboard strokes slowly, screen magnification software users, screen reader users working with sighted colleagues, keyboard only users and those navigating using voice recognition software. However, Success Criterion 2.4.1 does not require that they be visible when they do not have focus, and links that are visible only when they have focus can meet this success criterion.

I would personally consider that the new 3.2.7 is an encouragement to always make links visible and as "skip links" are not "needed to progress or complete a process", the above paragraph is sufficient to address the question for 2.4.1 without discouraging people to gain in accessibility by making the links always visible.

**Comment by alastc** [comment] 2021-02-02 21:56
Hi @CarynPagelTR,

Thanks for raising this. The [latest version](https://w3c.github.io/wcag/understanding/visible-controls.html) uses a different approach which focuses on the information for that control being available is visible.

There is also an exception that covers this scenario: 
> The component is provided specifically to enhance the experience for keyboard navigation;

I'll close this as the source of the issue is gone, but please do raise any new issues on the new text, it will be going out for review again.

**Closed by alastc** 2021-02-02 21:56 UTC
Labels: 3.2.7 Hidden controls, Member Comment, WCAG 2.2
