### ISSUE TITLE
2.4.12 Focus not Obscured (Minimum) and user opened / controlled content

### ISSUE THREAD

**Issue by melaniephilipp** [w3c/wcag#2751] opened 2022-10-25 15:17 UTC
While implementing WCAG 2.2’s 2.4.12 Focus not Obscured (Minimum), we encountered a scenario we’d like the Understanding document to provide clarification on: The applicability of 2.4.12 where content that can be opened / closed by the user impacts the visibility of other focusable content.

Regarding movable content, the Understanding document clarifies: “If the interface is configurable so that the user can move toolbars and non-modal dialogs around, then only the initial positions of user-movable content would be considered for testing and conformance of this success criterion.”

That doesn’t seem to directly address content where opening / closing of overlay content can be controlled by the user, that is: where there is no failure of 2.4.12 in the default state of the page, but when the user opens overlay content, focusable elements could end up entirely behind the content while the content is open.

More detailed examples follow.

One impactful and wide-spread example is a chat interface that is collapsed into a button in its default state. In that state, there isn’t a 2.4.12 failure. However, when the user opens the chat interface, it entirely covers some focusable content. For this scenario let’s also say that any content behind the chat can be accessed by collapsing the chat to access it again - without losing any of the chat activity.

Closely related are the messaging popup panels in the lower right corner of sites like Facebook and LinkedIn.

Another example is popup content that is actively opened / closed by the user on mouse click or Enter (as opposed to opening on hover or focus), sometimes referred to as a “toggle tip”. Content behind the “toggle tip” could contain focusable elements that are entirely covered. Toggle tips aren’t (usually) modal, so the user could tab to elements entirely behind the toggle tip overlay if they don’t choose to close it.

Those are just a few examples that come to mind.

Clarification along the lines of the one given for movable content would be very welcomed. 

Thank you.

**Comment by detlevhfischer** [comment] 2022-10-26 07:37
For keyboard users, opening additional content would typically involve moving the keyboard focus to the trigger that then opens content (and either set kb focus to the newly opened content (modal dialogs) or leave it on the trigger where a repeat activation would then close content (custom tooltips or popup menus). To me, this seems to mitigate the risk that any focus points would become obscured by actively opened content.  That's why I don't think the behaviour would generally cause problems for keyboard users as long as focus management works as it should. In situations where the focus is not trapped by the additinonal content (say, with non-modal dialogs), I think users can be expected to actively close content that they have actively opened before. It may be good to add a clarification to the 2.4.12 understanding text.

**Comment by bruce-usab** [comment] 2022-11-01 18:48
@melaniephilipp is the explanation @detlevhfischer  provided sufficient?  If so, please close this issue.  Else, please expand on what your are looking for.

**Comment by melaniephilipp** [comment] 2022-11-01 19:38
Hi @bruce-usab 

When I asked for "Clarification along the lines of the one given for movable content would be very welcomed." I could have added "in the Understanding document, to be more clear.

Based on @detlevhfischer  apparent support for the idea of adding a clarification to the understanding text:

My suggestion would be to divide the second paragraph of the Intent section into two paragraphs with an additional sentence added to the end of the second paragraph.

> Where other content can overlap with a focused item, the focused element should not be hidden. Typical types of content that can overlap focused items are sticky footers, sticky headers, or non-modal dialogues. As a user tabs through the page, these layers of content can obscure the focused item, including the focus indicator. 
> 
> If the interface is configurable so that the user can move toolbars and non-modal dialogs around, then only the initial positions of user-movable content would be considered for testing and conformance of this success criterion. Similarly, if the interface contains content that the user can open / close or expand / collapse, only the default state of that user-controlled content would be considered. 

Also, I think the instance of “dialogues” should be “dialogs”?

Thank you

**Comment by bruce-usab** [comment] 2022-11-01 19:56
Excellent, thank you.  I am going to mark this issue as Ready for Survey because I think we have clarity as to the changes you are looking for in Understanding.

**Comment by alastc** [comment] 2023-01-25 23:35
Picking up the conversation from the last meeting, how about something like:

<hr>

Where other content can overlap with a focused item, the focused element should not be hidden. Typical types of content that can overlap focused items are sticky footers, sticky headers, or non-modal dialogues. As a user tabs through the page, these layers of content can obscure the focused item, including the focus indicator.

If the interface is configurable so that the user can manually open, close, and/or move components such as toolbars and non-modal dialogues, then there needs to be a configuration that does not obscure focused items. However, if such components automatically open and obscure focused elements, that would fail this criterion. For example, a navigation drop-down which opens when focused, but does not close when focus moves to other elements would not pass if it covered focusable elements.

**Comment by alastc** [comment] 2023-01-27 16:42
@mbgower we've tweaked the suggested text in the comment above, does that work for you?

**Comment by bruce-usab** [comment] 2023-01-27 16:44
I am noting that this edit to Understanding is consistent with exceptions in other SC and general principle <q>unless a change is initiated by the user</q>

It is essentially a bug (and a failure against this SC) if something (like a hamburger menu) stays open on keyboard focus after keyboard focus is removed &mdash; when mouse-over behavior (appear/disappear) works as expected.

Selecting (click or return key) is not in scope for this SC, since that is a very different scenario.

**Comment by mbgower** [comment] 2023-01-30 21:34
I put comments into the PR. The challenge we have is that there is a gap between a menu (which I'm hoping everyone agrees should close on loss of focus) and an expandable side bar.
The latter can have two basic functions. In one, the user expands it and it 'pushes' the main content over (main content section reduces in width). In the other, it overlays  the main content.
I hope it's clear that in the former, the focus will NEVER be obscured.
In the latter, it's entirely possible for the focus to get obscure.
IN some implementations, the sidebar collapses when an item in it is selected (and the main content updates). In addition, some implementations collapse the sidebar if the user focuses right out of it into the main content.
The latter also has a complementary behaviour, where when the user clicks in the main content area, the sidebar collapses.

In a different implementation of the latter, the side bar never collapses until the user actually collapses it by clicking on the collapse button. I need hardly say that this poses more potential problems for keyboard users, and there doesn't seem to be any GOOD reason to do it. IMO, this _should_ fail this new criterion, and some interactions would have to be updated (including some of the behaviour of the side bar on https://www.w3.org/TR/WCAG21/).

**Comment by mbgower** [comment] 2023-01-30 21:44
For things like the LInkedIn example pointed out on Tuesday's call, I think there are some relatively easy ways this could be implemented without obscuring focus. I'd like to take those on a case by case basis, but I have so far not seen an interaction that could not be done in such a way that focus was not obscured.

**Comment by bruce-usab** [comment] 2023-02-03 18:06
Apologies, as I think if I had been more on the ball with the backlog call today (2/3) we might have been able to closet this one out.

> I think there are some relatively easy ways this could be implemented without obscuring focus.

I agree with not giving anti-patterns too much attention, but it seems worth it to keep chewing on to me.

It seems common enough that keyboard focus behavior is poor as comparted to on-hover behavior. 

Yes, we all agree that menus should close on loss of focus.

Agreed, if an expandable sidebar menu 'pushes' the main content over (main content section reduces in width), then focus will NEVER be obscured.

> In a different implementation of the latter, the side bar never collapses until the user actually collapses it by clicking on the collapse button. I need hardly say that this poses more potential problems for keyboard users, and there doesn't seem to be any GOOD reason to do it.

> IMO, this should fail this new criterion...

@mbgower please clarify.  In your opinion, **does** such an implication fail 2.4.12?  (Because IMHO it is poor UI, but not a fail necessarily. 

> and some interactions would have to be updated (including some of the behavior of the side bar on https://www.w3.org/TR/WCAG21/).

Please describe the problematic WCAG sidebar behavior in more detail, so I might better understand your reference.

**Comment by mbgower** [comment] 2023-02-03 21:51
> @mbgower please clarify. In your opinion, does such an implication fail 2.4.12? (Because IMHO it is poor UI, but not a fail necessarily.)

Here's the current SC wording:

> When a [user interface component](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html#dfn-user-interface-component) receives keyboard focus, the component is not entirely hidden due to author-created content.

The way the SC wording is now, if the LinkedIn messaging region, which opens from the bottom of the page, at any time  completely obscures a link behind it, it will fail this SC.

I've posted two images of that interaction below. In the first, the Messaging 'popup' (for lack of a better term) is collapsed and ALMOST obscures the last chevron button (>) in the Promotion/Ad area. Two thirds of the area above it is grey space.

In the second, the Messaging pane is expanded (although I have obscured personal data with a big black rectangle; ignore that). It's mainly taking up that grey space, but is does covers all the chevrons in the Promotion area and partially covers the i icon in the LinkedIn News section.

![Screenshot 2023-02-03 at 1 28 05 PM](https://user-images.githubusercontent.com/14298245/216714317-b30809ce-38d6-4482-ad86-7bec9dc8bd1e.png)
^ Messaging pane collapsed

![Screenshot 2023-02-03 at 1 28 17 PM](https://user-images.githubusercontent.com/14298245/216714638-56a3b64c-bf87-4448-8814-48acaf46ddbd.png)
^ Messaging pane opened

Now, bulleted items in the LinkedIn News -- at least at the magnification, etc I have -- will never entirely be obscured, since the entire news item takes focus. I'm adding in a screen detail to show how one of these is not fully obscured behind the messaging. The blue focus indicator is clearly visible for a good chunk of the news item.

![image](https://user-images.githubusercontent.com/14298245/216715609-28aa6d52-56ee-4f66-a798-b6d2fa406605.png)
^ Message partially obscuring news item with focus

But the right facing 'chevron' buttons in the Promoted section are fully obscured.
The only wiggle room I think there is is what exactly is scoped by this note (which IMO should be immediately under the normative text)

> If the interface is configurable so that the user can move toolbars and non-modal dialogs around, then only the initial positions of user-movable content would be considered for testing and conformance of this Success Criterion.

I would like some content in the Understanding document that clarifies that something that can be expanded/opened is not "user-movable" and does not fall in this exception.

In other words, the LinkedIn example SHOULD fail this criteria. BTW, note that the _only_ ones that are fully obscured in my view of the LinkedIN site are those 'chevrons'. There are other items that take focus without being fully obscured, even within that Promoted section. I've put in a screen snippet showing how a good portion of the item and its blue focus indicator are clearly visible.
![image](https://user-images.githubusercontent.com/14298245/216716218-582952a3-5cf4-4825-a640-9c1735fdf68a.png)

--- 

Final note on this: 
It may be worthwhile to explore whether we regard ads to be 'author created content'. I don't personally, but I know there is not consensus on that.  I think we could have potential wiggle room to allow sidebars to obscures that crap that gets shoved on the right sides of many sites if we clarified that 'author-created' does not include advertising, for the purposes of this SC.

**Comment by bruce-usab** [comment] 2023-02-03 22:23
Here's the current SC wording:

> When a [user interface component](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html#dfn-user-interface-component) receives keyboard focus, the component is not entirely hidden due to author-created content.

>> The way the SC wording is now, if the LinkedIn messaging region, which opens from the bottom of the page, at any time completely obscures a link or control behind it, it will fail this SC.

Uh oh.  That was not my understanding of this SC.  If that were the case, the SC would be more like:

> When a component receives keyboard focus, <del>the</del> <ins>no other keyboard focusable</ins> component is <del>not</del> entirely hidden due to author-created content.

**Comment by mbgower** [comment] 2023-02-06 19:05
yeah, I should have worded that more carefully:
> The way the SC wording is now, if the LinkedIn messaging region, which opens from the bottom of the page, at any time completely obscures the link or control behind it that has focus, it will fail this SC.

**Comment by bruce-usab** [comment] 2023-02-07 17:31
Okay, again we are in rabid agreement.

**Comment by melaniephilipp** [comment] 2023-02-08 20:40
Two concerns:

**Comment by melaniephilipp** [comment] 2023-02-08 20:54
Two concerns:

1. For the LinkedIn messaging panel example, things get super complicated to design "free space" behind the panel when you take into account narrower screen widths (or zoomed in pages) where the left column disappears and also the fact that things behind the panel can scroll.
2. Am I wrong in thinking that this would have a profound effect on chatbots? Again, taking into account varying screen widths / zoom levels and scrolling content?

Can we think in terms of differentiating scenarios along the lines of 1) content that is not meant to be open while the rest of the page is being viewed (for example hamburger menus or mega menu submenus) and 2) content that may be open or closed (user discretion) while the rest of the page is viewed (for example chat bots and messaging panels and form field level tooltips)?

**Comment by melaniephilipp** [comment] 2023-02-08 21:40
And as I was just messaging in LinkedIn, I realized that the message panel has yet another panel that can open to the left of the main message panel to respond to a message in the panel, further complicating the scenario of covering other focusable content. But also... if you don't want the panels open, you have the choice of collapsing them and opening the whole messaging activity in a dedicated messaging page. It's really in the user's control to decide if the open panels are a problem or a convenience.

**Comment by WilcoFiers** [comment] 2023-02-10 13:02
My 2 cents.

I'm pretty concerned that if we're too strict about things like opened chat boxes that devs are going to simply trap the keyboard focus in the chat, while leaving the page interactive for mouse users. Anything else may very well require a complete overhaul of the layout of the page.

I think the way to do this is to say that "author-created content" means; content rendered 1. not by the user agent, and 2. not activated by the user. I.e. If the user clicked a button to open something, they are responsible for closing it. But if that thing opened on a load, on focus / hover, on a timeout / on some other external event outside the user's control then the author is responsible.

So a page that pops up a chat automatically after 30 seconds on the page could fail this SC. A chat that opens when the user clicks the chat button could not fail the SC.

**Comment by mbgower** [comment] 2023-02-10 15:59
> I was just messaging in LinkedIn, I realized that the message panel has yet another panel that can open to the left of the main message panel to respond to a message in the panel, further complicating the scenario of covering other focusable content. But also... if you don't want the panels open, you have the choice of collapsing them and opening the whole messaging activity in a dedicated messaging page. It's really in the user's control to decide if the open panels are a problem or a convenience.

So there are a couple of things here. If a user has to discover a bunch of not necessarily obvious workarounds to figure out how to see where the keyboard focus is, at what point is that a problem? To me, the designer of the system has to have some responsibility in this.

Remember, we're talking about the indication of interaction for a keyboard user here. If the user opens up a second panel to respond to a message, I'm assuming the focus is right there? If that secondary panel persisted after the user dealt with the message or navigated away from it, basically obscuring even more of the interaction, are we saying that's okay because the user opened it? Doesn't the author have some responsibility to actually close things the user is no longer interacting with?

--- 

We've been dealing with similar interactions since the Focus Not Obscured was first proposed. We haven't run into any situations where there wasn't a fairly straightforward approach to ensure the focus was not obscured.

In the LinkedIn example, they could better define their columns so there is no overlaps, they could tighten up their responsive design (this isn't a problem at all break points), they could stack their right side content areas... There are a lot of ways this could 

If they wanted to get more heavy duty, they could, as @WilcoFiers suggests/cautions, make the message area into a non-modal region with its own tab ring and dedicate a key that allowed a user to move focus to and away from it. If the intent is to allow a user to have essentially a two-region parallel interaction, isn't that a more equivalent interaction for the keyboard user anyway?

>  not activated by the user

So, effectively, all dynamic interactions on the page are not the authors responsibility to manage in regard to focus handling. That seems like an awfully curtailed definition of author responsibility. It's not like the user agent created that messaging panel.

> Anything else may very well require a complete overhaul of the layout of the page. 

I've heard that cited as arguments against almost every new requirement introduced during my tenure. We can say the same for Pointer Gestures, Dragging, Reflow, etc. Yes, they have required teams I work with to alter their design processes, implementations and testing.
The defendable response has been the same for all of them: organizations like LinkedIn refresh their UI on a pretty regular basis. When they decide to adopt 2.2, they're going to have a number of considerations to iterate through to meet the new requirements.

The bigger question, to me, is 1) is there a problem that needs to be solved (I'd say yes), 2) does this SC solve a reasonable portion of it (I'd say yes).  When the item with focus is not in evidence on a page, I think that's a pretty clear indication of an accessibility challenge for any sighted user who relies on interaction over the keyboard API.

**Comment by mbgower** [comment] 2023-02-10 16:14
@melaniephilipp I'll pursue seeing if we might be able to leverage a similar approach to 2.5.1 in regard to there being 'a way' to operate where focus is not obscured.

**Comment by mbgower** [comment] 2023-02-10 17:36
BTW, the little emoji icon in GitHub provides a nice little microcosm of the non-equivalency of mouse  vs keyboard on some of these things.
![image](https://user-images.githubusercontent.com/14298245/218156318-2b8b653e-1cdd-4eec-b411-e01f8a0438f2.png)

When you activate it, it reveals a list of responses
![image](https://user-images.githubusercontent.com/14298245/218156503-6cfd9cc8-dde6-4cba-bc19-aa2a4c548d6f.png)

You can tab through those things, and then keep tabbing right out of them _and the toolbar doesn't go away_. It persists. At my regular resolution and standard magnification, this doesn't fail Focus Not Obscured, because there is nothing that takes focus behind it.

But at a certain magnification level just before a breakpoint comes where it is repositioned, it actually gets much closer to the "edited" dropdown and timestamp UICs to its left 
![Screenshot 2023-02-10 at 9 23 10 AM](https://user-images.githubusercontent.com/14298245/218157136-1ce473bb-580e-4feb-8131-2bfc26302f26.png)
When I activated the emoji toolbar, it actually fully obscures these UICs
![Screenshot 2023-02-10 at 9 25 32 AM](https://user-images.githubusercontent.com/14298245/218157395-312487c4-4af8-4020-a936-45017005e219.png)

The good news for Github is that neither focus indicator is entirely obscured by this. Still a tiny bit of the indicator stays visible above the toolbar
![Screenshot 2023-02-10 at 9 23 32 AM](https://user-images.githubusercontent.com/14298245/218157615-2f673929-a2e1-4502-a392-c32e1171e640.png)
![Screenshot 2023-02-10 at 9 23 40 AM](https://user-images.githubusercontent.com/14298245/218157654-ae458968-de4d-48d5-9a92-06a05bc89675.png)

But for those of you who can see, either my screen snippets of the actual interaction in github, you have no idea what the focus is actually on. So not a great experience.

Now, for a pointer user, all they need to do to dismiss the toolbar if it gets in therir way is click _anywhere_ else on the screen -- in other words, put the point of interaction anywhere else and the toolbar, rightly, goes away. But for the poor old keyboard user, even though they have clearly left the interaction of adding an emoji to a comment, they have to figure out how to get back to the toolbar and then dismiss it, and then return to wherever they were. 

To me, that is clearly not an equivalent experience or facilitation. Also, it's clearly a super easy thing to resolve. When the keyboard focus leaves the toolbar, it just needs to go away. Then there would be no need to worry about breakpoint differences, etc.

**Comment by alastc** [comment] 2023-02-20 14:45
From the Friday meeting, @mbgower was going to try and come up with some proposed text for the understanding doc.

**Comment by mbgower** [comment] 2023-03-01 15:55
BTW, I'm looking at a team presentation this morning on a full web-based design tool, and thought I'd just capture an image, because it shows a complex web interaction much closer to a traditional desktop design application.

This is approaching the use case that was intended when the Note about excepting _user-movable non-modal dialogs and toolbars_ was created. (Although ironically, in this particular interaction, the toolbars are NOT user movable, as far as I know). 
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/14298245/222189281-84cb7f11-2562-49d4-9aa6-4daa3a44d206.png">
^ A full design palette, with a left-side region for selecting new components, a center workspace region, and a right-side properties regions, that updates its content based on whatever object is selected in the workspace.

This interaction is a great opportunity to emphasize the need for facilitating keyboard equivalency. I hope it's super obvious that without coming up with a region-level interaction model, such a complex page would be effectively unworkable with a keyboard.

Note that there is little potential in this design to fail Focus Not Obscured. But I hope it's easy to envision how the problems with keyboard equivalency I discussed previously in this thread complicate the discussion:
- if we just allow stuff to overlay the main content without regard to its effect on keyboard facilitation, we are perpetuating and possibly worsening the trend (because now teams can point to the Focus Not Obscured guidance and say "Look, the AGWG is saying it's totally fine for us to shove all this stuff overtop of the main content. A user can still _get there_ by keyboard eventualy").

---

I'll try to come up with something that fairly succinctly points out the potential problems for keyboard users that are compounded when designs allow the item with focus to be entirely obscured.

**Comment by mbgower** [comment] 2023-03-08 20:07
@WilcoFiers reflagging the changes I've made to address in https://github.com/w3c/wcag/pull/3083 for your review. Thanks!

**Comment by melaniephilipp** [comment] 2023-03-20 19:23
@mbgower Can you please help me understand how what you are advocating for (no allowance for user opened/closed content to fully cover focusable elements) would impact something I see currently on Verizon's website? 

I have two screenshots below. One shows a Verizon chat window before opening it and one is after opening it. The chat is on a webpage for researching cell phones. When open, the chat popup covers various focusable elements as one scrolls the page or navigates from page to page. 

In this case, if someone WANTED to leave the chat window open so they could move around a single page or to other pages in the site, for example to get info about various phones or mobile plans, or whatever, while chatting, this SC would not allow them to leave that window open?  

And, if I'm misunderstanding what you are advocating for, please set me straight! 

Thank you in advance!

![image](https://user-images.githubusercontent.com/16922124/226444152-29df8ccc-aa80-4c57-858f-5081108f726e.png)
![image](https://user-images.githubusercontent.com/16922124/226444206-a8cd59d8-74bc-41f2-a4a8-4b0cecfa5ece.png)

**Comment by patrickhlauke** [comment] 2023-03-20 23:13
@melaniephilipp coincidentally, I was thinking along similar lines earlier over here (if we imagine/assume that the "chat with us" would be a good condidate for a non-modal dialog) https://github.com/w3c/aria-practices/issues/2536#issuecomment-1476851864

**Comment by scottaohara** [comment] 2023-03-21 10:36
@mbgower regarding your popup emoji example from github, and related to my comment on this PR - https://github.com/w3c/wcag/pull/3083#pullrequestreview-1348291322. Would the popup content persisting after focus left it be a problem if it could be dismissed by the Esc key?

The problem with light dismissing (closing when focus leaves the popup) stuff like that is for a sighted keyboard user, they can see that it's gone. but for someone using a screen reader, they may not be immediately aware that they've tabbed out of the component and in trying to find it again, it's been closed and they have to redo the process of opening the popup.  Granted, there are certain popups like listboxes and menus where there is long standing behavior that they will light dismiss when they are left via tab key. But more generic types of popups - a list of links, a disclosure widget whose content overlays others (a toggle tip, which doesn't necessarily have a "tooltip" containing element role), or even a non-modal dialog (keyboard focus is not natively trapped in these by default). It can be awkward and unexpected for these sorts of components to auto-close.  

While I agree we don't want to have people jump through hoops to figure out how to dismiss an element that is obscuring other content, if there are common mechanisms in place that allow parity for users to dismiss or minimize content so that it is no longer obscuring other focusable elements (e.g., esc key, click/tap outside to dismiss), I think those should be considered as a way to unobscure content and help pass this SC.  Otherwise, all popups will need to keyboard trap or light dismiss when tab key exits, and I think this SC would be problematic if it was essentially requiring, without stating, that all popups must either trap focus or light dismiss when focus leaves them - which after reading these discussions, is what I'm understanding this rule as requiring now.

**Comment by melaniephilipp** [comment] 2023-03-21 12:10
@patrickhlauke @scottaohara Thank you for your perspectives. 

It seems that this is one of those scenarios where in some cases it would be strongly preferable to have content "light dismiss" and others where it would be strongly preferable to leave control with the user and others somewhere in between and could go either direction depending on the use case and the user.

When I find myself wrestling with "it depends" scenarios, I (almost) always go in favor of leaving the control with the user (in this case to dismiss, or not, the thing THEY opened). I would really like to see user opened / controlled content treated the same as user movable content in the understanding document.

**Comment by mbgower** [comment] 2023-03-22 17:23
@melaniephilipp I believe the wording [committed as a note](https://github.com/w3c/wcag/pull/3083/commits/b2476e04e6294cd51192cc4e91650e34acef22d9) should address much of this problem space -- without perpetuating what I hope folks agree tends to be a 'second class' keyboard experience. 

> Where content disclosed by the user can obscure other content, if the user can reveal the item with focus without moving keyboard focus (for example, by dismissing with Esc), such disclosed content is not considered to fully obscure the item receiving focus.

The result of this would be that someone would for example be able to pass Focus Not Obscured by allowing the user to do any of the following where they'd opened content that obscured focus:
1. press Esc to dismiss/collapse a disclosure
2. adjust the viewport by pressing Up/Down arrows, page up/down, etc., to bring the item with focus into view
3. issue something like F6 to move between a non-modal dialog (chat window or whatever) and other content

The two key qualifiers are that 1) it is allowed where it is an action of the _user_ that obscures the item with focus 2) the item with focus needs to be brought into view without the user needing to adjust focus.

May need a bit of tweaking, but it feels pretty close.  @patrickhlauke, I _think_ this covers both true and faux non-modal interactions. A true non-modal should never obscure the item with focus, right? For non-modal-ish overlays, providing a keyboard shortcut for overlay interaction would resolve. For instance, in gmail, the Shift+Esc/Esc shortcuts allow me to put focus in the main inbox (when my compose overlay is in the way).

**Comment by mbgower** [comment] 2023-03-31 15:13
@melaniephilipp and @WilcoFiers and @patrickhlauke 

Have you had a chance to look at the additional information I've added to the understanding document, including the notes? Does this clarify things enough?

**Comment by melaniephilipp** [comment] 2023-03-31 17:28
@mbgower It's a bit difficult to follow what the resulting full page content is intended to look like with all the comments. 

But, the proposed note for the SC text looks reasonable for desktop: "Where content disclosed by the user can obscure other content, if the user can reveal the item with focus without moving keyboard focus (for example, by dismissing with Esc), such disclosed content is not considered to fully obscure the item receiving focus."

Are there implications for mobile interfaces with a screen reader turned on and where a keyboard isn't being used - so ESC or arrows keys can't be used? In other words, is mobile screen reader focus in scope for this SC? I think not, but want to be sure.

**Comment by mbgower** [comment] 2023-03-31 19:34
> @mbgower It's a bit difficult to follow what the resulting full page content is intended to look like with all the comments.

I will try to generate a preview.

> the proposed note for the SC text looks reasonable for desktop... Are there implications for mobile interfaces with a screen reader turned on and where a keyboard isn't being used - so ESC or arrows keys can't be used? In other words, is mobile screen reader focus in scope for this SC? I think not, but want to be sure.

Remember that this entire SC is about keyboard focus for user interface components. So if a scenario exists in a modality where such keyboard focus is not achieved (i.e., focus put on something that is not a UIC, or nothing whatever has keyboard focus) then the SC is not going to apply. In the scenario where you are talking about a gesture-based screen reader navigation, depending on the context, we are not even talking about interaction; just content review analogous to scrolling down a page without navigating it.

Conversely, it _is_ possible for a mobile interface to be operated by keyboard. There are already requirements in Keyboard, Focus Visible and Non-Text Contrast to be met. 

>All [functionality](https://www.w3.org/WAI/WCAG21/Understanding/keyboard#dfn-functionality) of the content is operable through a [keyboard interface](https://www.w3.org/WAI/WCAG21/Understanding/keyboard#dfn-keyboard-interface)

> Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.

> The visual [presentation](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast#dfn-presentation) of the following have a [contrast ratio](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast#dfn-contrast-ratio) of at least 3:1 against adjacent color(s):
> - User Interface Components
Visual information required to identify [user interface components](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast#dfn-user-interface-component) and [states](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast#dfn-state)...

This SC would add on the requirement that when a UIC has visible focus, it not be obscured or (in the case where the user has obscured it themself) the user be able to unobscure it.

**Comment by mbgower** [comment] 2023-03-31 21:16
@melaniephilipp I'm attaching a preview from my own system for you. I couldn't quickly figure out to generate a rawgit preview, so hope this will help!
[Understanding Focus Not Obscured.pdf](https://github.com/w3c/wcag/files/11126969/Understanding.Focus.Not.Obscured.pdf)

If this direction makes sense, I'll incorporate more of the about comments in the issue into the doc, and start getting some visuals and examples to help make it more understandable.

**Comment by mbgower** [comment] 2023-03-31 23:52
@alastc It took me a LONG time to find it, but I finally located the article I was talking about -- from Knowbility -- which tackles _some_ considerations relevant to this space https://knowbility.org/blog/2020/accessible-slide-menus

**Comment by melaniephilipp** [comment] 2023-04-03 20:55
@mbgower Thank you for the PDF! I think you have struck a good balance. The only thing that comes to mind is under the heading "User openable, persistent disclosures" it should mention as one of the approaches the ability to dismiss the opened content with something like the ESC key as is mentioned in the Note under the SC itself.

**Comment by mbgower** [comment] 2023-04-05 17:20
Thanks, @melaniephilipp. Not all the _persistent_ disclosures would be dismissible/collapsible with `Esc` (think about an accordion, for example). That said, I do list it as a method in the sub-topic "When the additional content is disclosed, it takes focus and the tab ring is constrained to the new content until it is dismissed".
>This modality is somewhat like a dialog, in that a user cannot navigate beyond the disclosed content by keyboard without dismissing it first (typically by pressing Esc).

I'll see if there's another place to work it in appropriately.

Now that I have a direction that seems to be working, I'll also attempt to get some complementary illustrations added.

**Comment by mbgower** [comment] 2023-04-06 00:04
Okay, I'll incorporate. Thanks!

**Comment by DanHolbrookQA** [comment] 2023-04-06 14:49
A small note on your edits @mbgower - I've been piloting this guideline with testing teams since the first draft as an internal standard, and we get asked about whether using the arrow to scroll the page passes this a lot. I got asked about this again today. Because it's so common, if that could be explicitly in the example, i.e. "(for example, by scrolling the page or dismissing with Esc)" it would helpful.

**Comment by mbgower** [comment] 2023-04-06 18:06
Thanks, Dan. I will work to incorporate that.

HOWEVER, to make sure we're on the same page, I need to address your "e.g." text. Since the sticky banner/footer is not content the **user** opened/disclosed, it would not meet the wording of the second note.
In other words, if the _author_ designs a sticky footer such that it obscures the item receiving focus, it will fail this SC. In fact, user challenges from such constructs were one of the primary motivators for this SC.

I hope the distinction is obvious. If I as a user starting tabbing through a new page only to find that through no action of my own I can't see where the focus is, that responsibility is the author's.

Contrast that with a **user** who while interacting with a page opens a chat window (or say a compose window in an online email application). There are still obvious ways the author can ensure focus is never obscured. But there are also possible situations where the user is given the power to switch modalities or views.

I'll work on making this crystal clear in the wording -- and may revise the note to make it clearer, since it's obviously still 
a point of confusion.

**Comment by DanHolbrookQA** [comment] 2023-04-06 18:22
@mbgower That's good to know, as I was concerned we were taking the teeth out this guideline with this second note, and we've been testing the situation I described as failures going back to when we just had Focus Visible.

I would ignore my (e.g.) suggestion then entirely, but (and this may be a separate issue) given the questions I've heard, I don't think that it's clear in the Understanding text that author-caused but user-solvable Focus Not Obscured issues are covered by the guideline.

**Comment by mbgower** [comment] 2023-04-06 18:48
@DanHolbrookQA thanks for that feedback.
I will work on something that magically combines clarity and concision in that note, and then elaborate in the Understanding document.

**Comment by mbgower** [comment] 2023-04-14 21:47
This issue is not resolved until https://github.com/w3c/wcag/pull/3083 is surveyed, adjusted, and merged

**Comment by mbgower** [comment] 2023-04-18 05:17
@rachaelbradley and @alastc 
I have now updated https://github.com/w3c/wcag/pull/3083 with an update to the existing note and the addition of a new note, along with matching changes in the Understanding document, which that I believe address the core points of this issue.

The Understanding document will certainly benefit from some illustrations and future tweaks, but I believe this is something that should be put in front of the working group.

I'm particularly concerned that while these are not normative changes, there may be perceptions that the notes need to be finalized as part of this last round of prep for the round of CR. Apologies for not getting it into survey this week.

**Comment by alastc** [comment] 2023-04-27 20:29
Closed by #3083, approved here: https://www.w3.org/2023/04/25-ag-minutes#item06

**Closed by alastc** 2023-04-27 20:29 UTC
Labels: Survey - Added, Understanding, WCAG 2.2, 2.4.12 Focus Not Obscured (Minimum)
