### ISSUE TITLE
WCAG 2.2 CR: New Features in WCAG 2.2 should show levels and SC numbers

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag#2677] opened 2022-09-14 19:44 UTC
To be consistent with WCAG 2.1's [section called New Features in WCAG 2.1](https://www.w3.org/TR/WCAG21/#new-features-in-wcag-2-1), the [New features in WCAG 2.2 section](https://www.w3.org/TR/WCAG22/#new-features-in-wcag-2-2) should also show the criteria numbers and levels of the new SC.  This establishes a quick way for groups that will likely be early adopters (e.g. ETSI, CEN/CENELEC) to incorporate the appropriate new criteria into broader standards, such as the EN 301 549. The EN currently focuses on Level AA conformance - not likely to change with the next update - so this change would provide an easy way to scan for which criteria to add.

**Comment by yatil** [comment] 2022-09-15 08:02
This is a duplicate of 

- #1807 

and will be addressed by Pull Request 

- #2667

if the Pull Request is merged, that is.

**Comment by alastc** [comment] 2022-11-10 19:45
Done in #2780

**Closed by alastc** 2022-11-10 19:45 UTC
Labels: Duplicate, WCAG 2.2
