### ISSUE TITLE
3.2.7 Hidden Controls – What qualifies as progress or completing a process? 

### ISSUE THREAD

**Issue by CarynPagelTR** [w3c/wcag#1442] opened 2020-09-18 20:49 UTC
On Behalf of Thomson Reuters 

This Success Criterion states: "Controls needed to progress or complete a process are visible … " 

Our teams are struggling to understand when a control is not impacting progress or completing a process. We think every control falls under one of these categories, no matter how minor their function. Therefore, the words "needed to progress or complete a process" may be unnecessary.

**Comment by rachaelbradley** [comment] 2020-09-29 17:47
Proposed response: The intent for this is to only apply to controls required to complete or progress a process. Process is defined as "series of user actions where each action is required in order to complete an activity."  Controls that are optional and controls that are not part of a series of actions are not considered part of this SC.

**Comment by patrickhlauke** [comment] 2020-09-29 18:40
afraid that's a bit of a non-answer, as it's unclear what can and can't be considered a process/activity. if a user wants to do something, than any step the user needs to take to achieve that is a process/activity.

**Comment by CarynPagelTR** [comment] 2020-09-29 19:10
In this definition of process, what is the definition of "activity"?

It's still unclear to me when a control would _not_ impact progress or completion of a process, so the language "needed to progress or complete a process" still feels unneeded.

**Comment by mraccess77** [comment] 2020-09-29 19:52
From this definition I'd assume pretty much anything is a process including bolding text, changing a user name, editing a group, expanded a widget or menu to read content or reach a menu item, etc. as these are part of activities.    Perhaps what we are aiming at is activities that align with those listed in 3.3.4 - legal, financial, or those that store user data.   I've made this suggestion before though and folks thought that was too limiting.

**Comment by rachaelbradley** [comment] 2020-09-29 20:05
Based on this conversation, I suggest we bring several rewording suggestions for the SC to AGWG for further conversation.

**Comment by alastc** [comment] 2021-02-02 21:57
Hi @CarynPagelTR,

Thanks for raising this. The [latest version](https://w3c.github.io/wcag/understanding/visible-controls.html) uses a different approach which focuses on the information for that control being available is visible.

I'll close this as the source of the issue is gone, but please do raise any new issues on the new text, it will be going out for review again.

**Closed by alastc** 2021-02-02 21:57 UTC
Labels: 3.2.7 Hidden controls, Member Comment, Survey - Ready for, WCAG 2.2
