### ISSUE TITLE
3.2.7 Hidden Controls – Because of language "at least one instance of the controls needs to be visible" within a page or process, a possible loophole may arise

### ISSUE THREAD

**Issue by CarynPagelTR** [w3c/wcag#1440] opened 2020-09-18 20:47 UTC
On Behalf of Thomson Reuters 

Current language states: "In some cases, controls are provided in multiple locations on a page or at multiple points within a process. In these cases, at least one of the instances of the controls needs to be visible without user interaction." 

How deep do we expect users to go to get to a control? For example: An "add" button exists in two places. One place is inline with the associated content, and this control is hidden until focus or hover happen. The other place is in a "more" menu that's nested inside an accordion element, and this control is not visibly hidden. Because of the multiple extra steps needed to get to the control that's not visibly hidden, are we actually helping people by allowing this loophole to be part of this Success Criterion?

**Comment by alastc** [comment] 2021-02-02 21:55
Thanks for raising this. The [latest version](https://w3c.github.io/wcag/understanding/visible-controls.html) uses a different approach which focuses on the information for that control being available is visible.

There is also a note on the SC text which states: "User interface components can be available through other visible components such as sub-menus, edit buttons, tabs, or thumbnails of media."

I'll close this as the source of the issue is gone, but please do raise any new issues on the new text, it will be going out for review again.

**Closed by alastc** 2021-02-02 21:55 UTC
Labels: 3.2.7 Hidden controls, Member Comment, WCAG 2.2
