### ISSUE TITLE
Identify Input Purpose link doesn't redirect to "Input Purposes for user interface components section"

### ISSUE THREAD

**Issue by maia-miller** [w3c/wcag#3119] opened 2023-03-27 01:19 UTC
In the definition of 1.3.5 Identify Input Purpose, the phrase in the second bullet "Input Purposes for user interface components section" redirects to an anchor that doesn't exist on the page.

It's supposed to link to this page: https://www.w3.org/TR/WCAG21/#input-purposes

**Comment by msayoung** [comment] 2024-02-27 16:32
Duplicate of:  https://github.com/w3c/wcag/issues/2962

**Comment by patrickhlauke** [comment] 2024-02-27 20:02
Indeed, duplicate. Closing this one in favour of #2962

**Closed** 2024-02-27 20:02 UTC
Labels: Technical (bug)
