### ISSUE TITLE
Odd unlinked references in Understanding 1.4.3 and 1.4.6

### ISSUE THREAD

**Issue by mooribund** [w3c/wcag#4120] opened 2024-10-28 01:40 UTC
Hello! The "Understanding" pages for [1.4.3 (Contrast (Minimum))](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) and [1.4.6 (Contrast (Enhanced))](https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced.html) have what seem to be citations or references but are not actually linked to anything, and the pages do not have any sort of bibliography to which these might be referring. 

In the ["Rationale for the Ratios Chosen" section](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html#rationale-for-the-ratios-chosen), for instance, there's the following:

> A contrast ratio of 3:1 is the minimum level recommended by [[ISO-9241-3]] and [[ANSI-HFES-100-1988]] for standard text and vision.

It seems like the two parts in `[[]]` are meant to be links or citations of some kind. Searching this repo for `ISO-9241-3` turns up this [Guide to WCAG 2 XML file](https://github.com/w3c/wcag/blob/bfa7f4c5c3b1389d8756f84b55c7edf26c595c32/wcag20/sources/guide-to-wcag2-src.xml#L782) that seems to include the citation that should be linked to the above example.

**Comment by patrickhlauke** [comment] 2024-10-29 16:34
@kfranqueiro I think I may have mentioned these sorts of things before ... it seems it's using respec-like syntax, but they're not being processed as such

**Comment by kfranqueiro** [comment] 2024-10-29 16:40
Yes, there are multiple related issues like this that I've written down together in my notes, including #2535 and #2756.

**Comment by kfranqueiro** [comment] 2024-10-29 19:58
Looking more closely, I think this particular issue is referencing the same instances as #2756, so I'm inclined to close this as a duplicate of that. I may even close that one and keep #2535 as the original, as I think I ended up mentioning the same page there. I'll post a more detailed update there.

**Closed by kfranqueiro** 2024-10-29 19:58 UTC
