### ISSUE TITLE
2.4.13 Term "electronic publication" not needed

### ISSUE THREAD

**Issue by kiyochika** [w3c/wcag#1429] opened 2020-09-18 11:24 UTC
I've reviewed the SC with our accessibility team and we consider that the definition of "electronic publication", which is the Glossary term, needs a tester's subjective judgment and therefore it leads to ambiguity for testers and is not testable.

Then, we felt that it still works fine without the phrase "electronic publication" to meet the intention of this SC, so we suggest the following change.

From:

> When a web page or set of web pages is an electronic publication with pagebreak locators, a mechanism is available to navigate to each locator and each locator maintains its place in the flow of content, even when the formatting or platform change.

To:

When a web page or set of web pages has pagebreak locators, a mechanism is available to navigate to each locator and each locator maintains its place in the flow of content, even when the formatting or platform change.

**Comment by alastc** [comment] 2021-01-08 12:48
@DavidMacDonald I'm fairly sure we discussed whether the "electronic publications" definition was needed, but I can't remember what the reasoning was that required it?

**Comment by DavidMacDonald** [comment] 2021-01-08 18:14
@alastc 
Shaun had concern that it had implications on Google docs which were unintended by the SC, and the term Electronic Publication solved that concern. Electronic Publication is a well understood concept in the industry and our definition tightens any ambiguity of those unfamiliar with the publishing industry and publications on the web. We don't anticipate disproportional disparity regarding inter-rater reliability. 
https://www.w3.org/TR/WCAG22/#dfn-electronic-publications

**Comment by bruce-usab** [comment] 2021-01-08 18:30
I am sympathetic to OP.

If we don't want 2.4.13 to apply to Google docs (or modern Word docs for that matter), then I think we need to tighten this up more.

What is the harm of requiring online word processing documents to programmatically expose print-oriented page numbers iff the document has them?

**Comment by mraccess77** [comment] 2021-01-08 19:11
It seems like this functionality is probably already support but some online word processors and is important to users.

**Comment by alastc** [comment] 2021-01-09 18:11
>  to programmatically expose print-oriented page numbers iff the document has them?

Assuming that isn't solved by the user agent (and it isn't in ePub agents or Browsers), it is the author providing the mechanism. 

It would mean things like Word/Docs/Slides/PPT need to provide a page navigation mechanism, assuming they have page markers.

I think the concern was that some word-processor like things don't really have a concept of pages, or at least it isn't the primary one. Or possibly it was to do with the editing interface compared to the end product? I.e. it would be difficult to do for the flexible editing interface, but once published as a doc/pdf/web-page it would be ok (or something, not sure).

**Comment by alastc** [comment] 2021-02-03 22:48
Hi @kiyochika,

With this and other issues raised, there is a [new version](https://w3c.github.io/wcag/understanding/fixed-reference-points.html) which removes the electronic publications definition. As the source of the issue is gone, I'll close this issue.

**Closed by alastc** 2021-02-03 22:48 UTC
Labels: 2.4.13 Fixed reference points, Public Comment, WCAG 2.2

**Comment by kiyochika** [comment] 2021-02-04 06:49
@alastc Thank you for your explanation. I will check the new version with our team.
