### ISSUE TITLE
Link in 2.1 failing F73

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#562] opened 2018-12-13 09:23 UTC
The bit near the top: This document is also available in non-normative formats, available from **Alternate Versions of Web Content Accessibility Guidelines 2.1**.

No underline or bold indicating the link. 

Should probably put a bug in for the spec redesign for aspect.

**Comment by awkawk** [comment] 2020-02-25 13:50
Closing as a duplicate of #1048 but keeping the newer one so we don't again forget about it.

**Closed by awkawk** 2020-02-25 13:50 UTC
Labels: Technical (bug)
