### ISSUE TITLE
!!! Understanding and How to Meet  links gone in WCAG 2.2 Latest published version !!!

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1809] opened 2021-05-17 07:10 UTC
Links on the right to Understanding and How to Meet gone in WCAG 2.2 Latest published version

https://www.w3.org/TR/WCAG22/

**Comment by jake-abma** [comment] 2021-05-17 07:12
@michael-n-cooper is this for you Michael?

**Comment by alastc** [comment] 2021-05-17 15:55
Yes, as the editor's version is ok I'm not sure what the problem is, I've emailed Michael directly.

**Comment by jake-abma** [comment] 2021-05-18 05:56
@alastc wrote:

> the editor's version is ok I'm not sure what the problem is

I never refer to the "editors version" but to the "Latest published version", that's the most recent stable one isn't it?
Think that is also what is referred to from all the different websites out there...

So that is probably the problem ;-)

**Comment by alastc** [comment] 2021-05-18 08:26
Indeed, I just meant that I can't fix it by updating something in the content. It is a template thing to do with how it is published to the /TR/ location, which I have no knowledge of.

**Comment by bruce-usab** [comment] 2021-05-18 13:50
> I never refer to the "editors version" but to the "Latest published version", that's the most recent stable one isn't it?

I understand the <q>latest published version</q> to be the version on the `tr` path.  But I think others might reasonable assume could mean the most recent iteration of the Editor's Draft (which, historically, are reasonably stable, polished, and the version I reference to check that I am up to speed.

@jake-abma , when you most recently used the phrase, which of these did you have in mind?  And does it matter if you are talking with a AG WG member, or a collogue?

- https://w3c.github.io/wcag/guidelines/22/
- https://www.w3.org/TR/WCAG22/

**Comment by patrickhlauke** [comment] 2021-05-19 00:02
As the broken one is the version that the public have now been asked to look at and comment on https://twitter.com/w3c/status/1392741675022303234 / https://www.w3.org/blog/news/archives/9052 ... it should probably be fixed with some urgency

**Comment by alastc** [comment] 2021-05-19 09:00
I'm very aware of that, unfortunately Michael is dealing with a non-work emergency at the moment. It is top of the list, but likely to be tomorrow (US time).

**Comment by yatil** [comment] 2021-05-22 14:12
This has now been fixed (as [announced on Twitter](https://twitter.com/alastc/status/1395770583221252103)).

**Closed** 2021-05-22 14:26 UTC
Labels: Technical (bug), WCAG 2.2
