### ISSUE TITLE
Missing link in Understanding 1.4.3

### ISSUE THREAD

**Issue by yatil** [w3c/wcag#293] opened 2017-06-09 06:29 UTC
## How to reproduce:

1. Go to https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html
2. Scroll down to Note 1 in the green box.
3. Click on the “CSS3 Values” link.
4. Realize that nothing actually happens.
5. Open an inspector and find out that the `href` attribute is not specified.

## How to fix:

Add a proper link.

## Something else?

It probably should read as “CSS Values Level 3” instead of “CSS3 Values”, but that is me nitpicking.

**Comment by awkawk** [comment] 2017-06-09 14:03
Actually this occurs twice in 1.4.3 and once in 1.4.6.  Will need to fix. Probably need to make it an official reference (like UNESCO, for example) and use the bibref element instead of a straight loc element.

**Comment by yatil** [comment] 2017-06-09 20:07
> use the bibref element instead of a straight loc element

I have no idea what this means, but if that makes the links work, all power to you! ;-)

**Comment by JAWS-test** [comment] 2020-01-29 06:52
The ticket can be closed because the problem is solved at https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html and https://www.w3.org/WAI/WCAG21/Understanding/contrast-enhanced.html (WCAG 2.1). Except for the WCAG 2.0 pages will continue to be updated

**Comment by fstrr** [comment] 2022-04-29 17:29
closing per last comment.

**Closed by fstrr** 2022-04-29 17:29 UTC
Labels: Editorial
