### ISSUE TITLE
Links point to nonexistent IDs in Understanding Success Criterion 4.1.3: Status Messages

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wcag#640] opened 2019-02-27 23:39 UTC
https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html

In this Understanding page, in the copy of the normative text of the success criterion, these links point to nonexistent element IDs:
“status messages”
“programmatically determined”
“assistive technologies”

In the Key Terms section, these links point to nonexistent element IDs:
“user agent”
“change of context”

**Comment by awkawk** [comment] 2019-02-27 23:42
Duplicate of #465

**Closed by awkawk** 2019-02-27 23:42 UTC
